query Unleash($team: Slug!) {
	team(slug: $team) {
		unleash {
			__typename
			name
			version
			releaseChannelName
			releaseChannel {
				name
				currentVersion
				type
				lastUpdated
			}
			allowedTeams(first: 20) @paginate {
				nodes {
					slug
				}
			}
			webIngress
			apiIngress
			metrics {
				apiTokens
				cpuUtilization
				cpuRequests
				memoryUtilization
				memoryRequests
				toggles
			}
			ready
		}
	}
}
