query KafkaTopics(
	$team: Slug!
	$orderBy: KafkaTopicOrder
	$filter: KafkaTopicFilter
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) @cache(policy: NoCache) {
	team(slug: $team) {
		slug
		kafkaTopics(
			first: $first
			last: $last
			orderBy: $orderBy
			filter: $filter
			before: $before
			after: $after
		) @paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
				startCursor
				endCursor
			}
			facets {
				environments {
					value
					count
				}
				pools {
					value
					count
				}
				labels {
					key
					value
					count
				}
			}

			edges {
				node {
					id
					__typename
					name
					team {
						slug
					}
					teamEnvironment {
						environment {
							name
						}
					}
				}
			}
		}
	}
}
