query KafkaTopics(
	$team: Slug!
	$orderBy: KafkaTopicOrder
	$filter: KafkaTopicFilter
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) @cache(policy: CacheAndNetwork, partial: true) {
	team(slug: $team) {
		slug
		kafkaTopics(
			first: $first
			last: $last
			orderBy: $orderBy
			filter: $filter
			before: $before
			after: $after
		) @paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
				startCursor
				endCursor
			}
			facets {
				environments {
					value
					count
				}
				pools {
					value
					count
				}
			}

			nodes {
				id
				__typename
				name
				team {
					slug
				}
				teamEnvironment {
					environment {
						name
					}
				}
			}
		}
	}
}
