query AlertsMetadata($team: Slug!) @cache(policy: CacheAndNetwork) {
	team(slug: $team) {
		environments {
			id
			environment {
				name
			}
		}
		totalAlerts: alerts {
			pageInfo {
				totalCount
			}
		}
		firingAlerts: alerts(filter: { states: [FIRING] }) {
			pageInfo {
				totalCount
			}
		}
		inactiveAlerts: alerts(filter: { states: [INACTIVE] }) {
			pageInfo {
				totalCount
			}
		}
	}
}
