query Alerts(
	$team: Slug!
	$orderBy: AlertOrder
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		slug
		alerts(first: $first, last: $last, orderBy: $orderBy, before: $before, after: $after)
			@paginate(mode: SinglePage) {
			pageInfo {
				startCursor
				endCursor
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
			}
			nodes {
				id
				name
				state
				query
				duration
				... on PrometheusAlert {
					alarms {
						action
						consequence
						since
						summary
						state
						value
					}
					ruleGroup
				}
				team {
					slug
				}
				teamEnvironment {
					environment {
						name
					}
				}
			}
		}
		totalAlerts: alerts {
			pageInfo {
				totalCount
			}
		}
	}
}
