query Applications(
	$team: Slug!
	$orderBy: ApplicationOrder
	$filter: TeamApplicationsFilter
	$rows: Int
) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		environments {
			name
		}
		applications(first: $rows, orderBy: $orderBy, filter: $filter) @paginate(mode: SinglePage) {
			pageInfo {
				totalCount
				endCursor
				startCursor
				hasNextPage
				hasPreviousPage
				pageEnd
				pageStart
			}
			nodes {
				__typename
				name
				environment {
					name
				}
				team {
					slug
				}
				status {
					state
				}
				deploymentInfo {
					timestamp
				}
				...AppInstancesStatus
			}
		}
	}
}
