query Workloads(
	$team: Slug!
	$orderBy: OrderBy = { field: STATUS, direction: ASC }
	$limit: Int
	$offset: Int
) @loading(count: 5, cascade: true) {
	team(slug: $team) {
		id
		apps(limit: $limit, offset: $offset, orderBy: $orderBy) {
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
			}

			nodes @loading(count: 14) {
				deployInfo {
					timestamp
				}
				name
				image
				...AppInstancesStatus
				env {
					name
				}

				status {
					state
				}

				instances {
					state
				}
			}
		}
	}
}
