query Applications($team: Slug!, $orderBy: ApplicationOrder, $filter: TeamApplicationsFilter)
@cache(policy: NetworkOnly) {
	team(slug: $team) @loading {
		applications(first: 20, orderBy: $orderBy, filter: $filter)
			@paginate(mode: SinglePage)
			@loading {
			pageInfo @loading {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
			}
			nodes @loading(count: 20) {
				name
				environment {
					name
				}
				status {
					state
				}
				deploymentInfo {
					timestamp
				}
				...AppInstancesStatus
			}
		}
	}
}
