query TeamSettings($team: Slug!) {
	team(slug: $team) {
		slug
		purpose
		slackChannel
		gitHubTeamSlug
		azureGroupID
		googleGroupEmail
		googleArtifactRegistry
		cdnBucket
		deploymentKey {
			created
			expires
			key
		}
		environments {
			name
			gcpProjectID
			slackAlertsChannel
		}
	}
}
