query Secret($secret: String!, $team: Slug!, $env: String!) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		environment(name: $env) {
			secret(name: $secret) {
				name
				environment {
					name
				}
				values {
					name
					value
				}
				workloads {
					nodes {
						id
						__typename
						name
						environment {
							name
						}
						team {
							slug
						}
					}
				}
				lastModifiedAt
				lastModifiedBy {
					name
					email
				}
			}
		}
	}
}
