query FetchSecretValues($secret: String!, $team: Slug!, $env: String!) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		environment(name: $env) {
			secret(name: $secret) {
				values {
					name
					value
				}
			}
		}
	}
}
