query Secret($secret: String!, $team: Slug!, $env: String!) @cache(policy: NetworkOnly) {
	me {
		... on User {
			isAdmin
		}
	}
	team(slug: $team) {
		viewerIsMember
		viewerCanElevate
		environment(name: $env) {
			secret(name: $secret) {
				name
				teamEnvironment {
					environment {
						name
					}
				}
				keys
				workloads {
					nodes {
						id
						__typename
						name
						teamEnvironment {
							environment {
								name
							}
						}
						team {
							slug
						}
					}
				}
				lastModifiedAt
				lastModifiedBy {
					name
					email
				}
			}
		}
		...SidebarActivityLogFragment
			@with(
				filter: {
					activityTypes: [
						SECRET_CREATED
						SECRET_VALUE_ADDED
						SECRET_VALUE_UPDATED
						SECRET_VALUE_REMOVED
						SECRET_DELETED
						ELEVATION_CREATED
					]
				}
				limit: 20
			)
			@mask_disable
	}
}
