query Secret($secret: String!, $team: Slug!, $env: String!) @cache(policy: NetworkOnly) {
	me {
		... on User {
			isAdmin
		}
	}
	team(slug: $team) {
		viewerIsMember
		environment(name: $env) {
			secret(name: $secret) {
				id
				name
				labels {
					key
					value
				}
				teamEnvironment {
					environment {
						name
					}
				}
				keys
				workloads {
					nodes {
						id
						__typename
						name
						teamEnvironment {
							environment {
								name
							}
						}
						team {
							slug
						}
					}
				}
				lastModifiedAt
				lastModifiedBy {
					name
					email
				}
				...ResourceActivityCardSecretFragment @mask_disable
			}
		}
	}
}
