query Bucket($team: Slug!, $name: String!, $environment: String!) {
	team(slug: $team) {
		environment(name: $environment) {
			bucket(name: $name) {
				publicAccessPrevention
				uniformBucketLevelAccess
				status {
					state
					errors {
						details
						message
					}
				}
				name
				environment {
					name
				}

				workload {
					name
					__typename
					environment {
						name
					}
					team {
						slug
					}
				}
			}
		}
	}
}
