query ResourceUtilizationForTeam($team: String!, $from: Date!, $to: Date!) {
	resourceUtilizationForTeam(team: $team, from: $from, to: $to) @loading(count: 2) {
		env @loading
		cpu {
			resource
			timestamp
			request
			usage
			requestCost
			requestCostOverage
			usageCost
		}
		memory {
			resource
			timestamp
			request
			usage
			requestCost
			requestCostOverage
			usageCost
		}
	}
	resourceUtilizationDateRangeForTeam(team: $team) @loading {
		from @loading
		to @loading
	}
	resourceUtilizationOverageCostForTeam(team: $team, from: $from, to: $to) @loading {
		sum @loading
		apps @loading(count: 1) {
			overage
			env
			app
		}
	}
}
