query ActivityLog($team: Slug!) @cache(policy: NetworkOnly) {
	team(slug: $team) @loading {
		slug
		activityLog(first: 10) @paginate(mode: SinglePage) @loading {
			pageInfo @loading {
				hasNextPage
				hasPreviousPage
				pageEnd
				pageStart
				totalCount
			}
			edges @loading(count: 10) {
				node @loading {
					__typename
					createdAt @loading
					actor
					createdAt
					environmentName
					message
					resourceName
					resourceType

					... on SecretValueAddedActivityLogEntry {
						secretValueAdded: data {
							valueName
						}
					}
					... on SecretValueRemovedActivityLogEntry {
						secretValueRemoved: data {
							valueName
						}
					}
					... on SecretValueUpdatedActivityLogEntry {
						secretValueUpdated: data {
							valueName
						}
					}
					... on TeamEnvironmentUpdatedActivityLogEntry {
						teamEnvironmentUpdated: data {
							updatedFields {
								field
								newValue
								oldValue
							}
						}
					}
					... on TeamMemberAddedActivityLogEntry {
						teamMemberAdded: data {
							role
							userEmail
							userID
						}
					}
					... on TeamMemberRemovedActivityLogEntry {
						teamMemberRemoved: data {
							userEmail
							userID
						}
					}
					... on TeamMemberSetRoleActivityLogEntry {
						teamMemberSetRole: data {
							role
							userEmail
							userID
						}
					}
					... on TeamUpdatedActivityLogEntry {
						teamUpdated: data {
							updatedFields {
								field
								newValue
								oldValue
							}
						}
					}
					... on UnleashInstanceUpdatedActivityLogEntry {
						unleashInstanceUpdated: data {
							allowedTeamSlug
							revokedTeamSlug
						}
					}
				}
			}
		}
	}
}
