projects:
  default:
    schema:
      - ./schema.graphql
      - ./.houdini/graphql/schema.graphql
      - ./houdini-directives.graphql
    documents:
      - '**/*.gql'
      - '**/*.svelte'
      - ./.houdini/graphql/documents.gql
