apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: test-a
  name: testapp
  namespace: test-a
spec:
  envFrom:
    - secret: test
  accessPolicy:
    outbound:
      external:
        - host: foo.com
          ports:
            - port: 5432
  image: europe-north1-docker.pkg.dev/nais-io/nais/images/testapp:latest
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
