overrides:
  "@sveltejs/kit>cookie": "^0.7.0"
  "@sveltejs/kit": "^2.70.2"
  postcss: "^8.5.23"
  form-data: "^4.0.6"
  brace-expansion: "^5.0.9"
  nanoid: "^3.3.17"
  esbuild: "0.28.1"

allowBuilds:
  esbuild: true
  houdini-core: true
  houdini-svelte: true

minimumReleaseAge: 20160
savePrefix: ""
minimumReleaseAgeExclude:
  - form-data@4.0.6
  - "houdini*"
  - "svelte"
  - "@sveltejs/*"
  - brace-expansion@5.0.9
  - nanoid@3.3.17
