overrides:
  cookie: "^0.7.0"

allowBuilds:
  esbuild: true
  houdini-core: true
  houdini-svelte: true

minimumReleaseAge: 20160
savePrefix: ""
minimumReleaseAgeExclude:
  - "houdini*"
  - "svelte"
  - "@sveltejs/*"
