overrides:
  cookie: "^0.7.0"
  esbuild: 0.28.2

allowBuilds:
  esbuild: true
  houdini-core: true
  houdini-svelte: true

minimumReleaseAge: 20160
savePrefix: ""
update:
  ignoreDeps:
    - typescript
minimumReleaseAgeExclude:
  - "houdini*"
  - "svelte"
  - "@sveltejs/*"
