query ResourceUtilizationForApp(
	$app: String!
	$team: String!
	$env: String!
	$from: Date
	$to: Date!
) @cache(policy: NetworkOnly) {
	resourceUtilizationForApp(
		app: $app
		env: $env
		from: $from
		team: $team
		to: $to
	) {
		cpu {
			timestamp
			request
			usage
		}
		memory {
			timestamp
			request
			usage
		}
	}
}
