query ResourceUtilizationForApp(
	$app: String!
	$team: String!
	$env: String!
	$from: Date
	$to: Date!
) @cache(policy: NetworkOnly) {
	cpu: resourceUtilizationForApp(
		app: $app
		env: $env
		from: $from
		resource: CPU
		team: $team
		to: $to
	) {
		timestamp
		request
		usage
	}

	memory: resourceUtilizationForApp(
		app: $app
		env: $env
		from: $from
		resource: MEMORY
		team: $team
		to: $to
	) {
		timestamp
		request
		usage
	}
}
