query UserTeams {
	me {
		__typename
		... on User {
			teams(first: 25) @paginate(mode: SinglePage) {
				pageInfo {
					hasNextPage
					hasPreviousPage
					pageEnd
					pageStart
					startCursor
					endCursor
					totalCount
				}
				edges {
					node {
						team {
							id
							slug
							purpose
						}
					}
				}
			}
		}
	}
}
