query UserTeams @cache(policy: CacheAndNetwork) {
	me {
		__typename
		... on User {
			teams(first: 25) @paginate(mode: SinglePage) {
				pageInfo {
					hasNextPage
					hasPreviousPage
					pageEnd
					pageStart
					startCursor
					endCursor
					totalCount
				}
				nodes {
					team {
						id
						slug
						purpose
						workloads(first: 10, filter: { states: [NOT_NAIS, FAILING] }) {
							nodes {
								status {
									errors {
										__typename
										level
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
