query UserInfo {
	me {
		... on User {
			id
			name
			isAdmin
		}
	}
	features {
		unleash {
			enabled
		}
		redis {
			enabled
		}
		valkey {
			enabled
		}
		kafka {
			enabled
		}
		openSearch {
			enabled
		}
	}
}
