query Applications(
	$team: Slug!
	$orderBy: ApplicationOrder
	$filter: TeamApplicationsFilter
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) @blocking @cache(policy: NetworkOnly) {
	team(slug: $team) {
		slug
		environments {
			id
			name
		}
		totalApplications: applications {
			pageInfo {
				totalCount
			}
		}
		applications(
			first: $first
			last: $last
			orderBy: $orderBy
			filter: $filter
			before: $before
			after: $after
		) @paginate(mode: SinglePage) {
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
				pageEnd
				pageStart
				startCursor
				endCursor
			}
			nodes {
				__typename
				id
				name
				environment {
					name
				}
				team {
					slug
				}
				status {
					state
				}
				deployments(first: 1) {
					nodes {
						createdAt
					}
				}
				instances {
					pageInfo {
						totalCount
					}
					edges {
						node {
							status {
								message
								state
							}
						}
					}
				}
			}
		}
	}
}
