query OpenSearchInstance(
	$environment: String!
	$team: Slug!
	$name: String!
	$orderBy: OpenSearchAccessOrder!
) {
	team(slug: $team) {
		slug
		environment(name: $environment) {
			openSearch(name: $name) {
				__typename
				id
				name
				version {
					actual
					desiredMajor
				}
				tier
				memory
				storageGB
				teamEnvironment {
					environment {
						name
					}
				}

				maintenance {
					window {
						dayOfWeek
						timeOfDay
					}
					updates {
						pageInfo {
							hasNextPage
							hasPreviousPage
							pageStart
							pageEnd
							totalCount
							startCursor
							endCursor
						}
						nodes {
							deadline
							description
							startAt
							title
						}
					}
				}

				workload {
					name
					teamEnvironment {
						environment {
							name
						}
					}
					__typename
					team {
						slug
					}
				}

				access(first: 10, orderBy: $orderBy) @paginate(mode: SinglePage) {
					pageInfo {
						hasNextPage
						hasPreviousPage
						pageStart
						pageEnd
						totalCount
						startCursor
						endCursor
					}
					edges {
						node {
							access
							workload {
								id
								name
								teamEnvironment {
									environment {
										name
									}
								}
								__typename
								team {
									slug
								}
							}
						}
					}
				}
				...OpenSearchManifestFragment
			}
		}
	}
}
