query TeamSettings($team: Slug!) {
	team(slug: $team) {
		slug
		lastSuccessfulSync
		purpose
		slackChannel
		deploymentKey {
			created
			expires
			key
		}
		environments {
			id
			environment {
				name
			}
			gcpProjectID
			slackAlertsChannel
		}
		externalResources {
			entraIDGroup {
				groupID
			}
			googleGroup {
				email
			}
			googleArtifactRegistry {
				repository
			}
			cdn {
				bucket
			}
			gitHubTeam {
				slug
			}
		}
		...SidebarActivityLogFragment
			@with(
				filter: {
					activityTypes: [
						TEAM_DEPLOY_KEY_UPDATED
						TEAM_CREATED
						TEAM_UPDATED
						TEAM_ENVIRONMENT_UPDATED
						TEAM_CONFIRM_DELETE_KEY
						TEAM_CREATE_DELETE_KEY
					]
				}
			)
			@mask_disable
	}
}
