query TeamSettings($team: Slug!, $viewerIsMember: Boolean!) {
	team(slug: $team) {
		slug
		lastSuccessfulSync
		purpose
		slackChannel
		deploymentKey @include(if: $viewerIsMember) {
			created
			expires
			key
		}
		environments {
			id
			environment {
				name
			}
			gcpProjectID
			slackAlertsChannel
		}
		externalResources {
			entraIDGroup {
				groupID
			}
			googleGroup {
				email
			}
			googleArtifactRegistry {
				repository
			}
			cdn {
				bucket
			}
			gitHubTeam {
				slug
			}
		}
	}
}
