query BigQuery(
	$team: Slug!
	$orderBy: BigQueryDatasetOrder
	$filter: BigQueryDatasetFilter
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) @cache(policy: NoCache) {
	team(slug: $team) {
		slug

		bigQueryDatasets(
			first: $first
			last: $last
			orderBy: $orderBy
			filter: $filter
			before: $before
			after: $after
		) @paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
				startCursor
				endCursor
			}
			facets {
				environments {
					value
					count
				}
				labels {
					key
					value
					count
				}
			}
			edges {
				node {
					id
					__typename
					name
					teamEnvironment {
						environment {
							name
						}
					}
					team {
						slug
					}
					workload {
						__typename
						name
						teamEnvironment {
							environment {
								name
							}
						}
						team {
							slug
						}
					}
				}
			}
		}
	}
}
