query SqlInstance($env: String!, $team: Slug!, $name: String!) {
	team(slug: $team) {
		slug
		environment(name: $env) {
			sqlInstance(name: $name) {
				__typename
				id
				name
				environment {
					name
				}
				cascadingDelete
				healthy
				#	type
				connectionName
				diskAutoresize
				diskAutoresizeLimit
				workload {
					name
					__typename
					environment {
						name
					}
					team {
						slug
					}
				}
				state
				tier
				cost {
					sum
				}
				metrics {
					cpu {
						cores
						utilization
					}
					memory {
						quotaBytes
						utilization
					}
					disk {
						quotaBytes
						utilization
					}
				}
				highAvailability
				backupConfiguration {
					enabled
					startTime
					retainedBackups
					pointInTimeRecovery
				}
				maintenanceWindow {
					day
					hour
				}
				maintenanceVersion
				version
				projectID
				database {
					name
					charset
					collation
					healthy
				}
				flags {
					pageInfo {
						hasNextPage
						hasPreviousPage
						totalCount
						pageStart
						pageEnd
						startCursor
						endCursor
					}
					edges {
						node {
							name
							value
						}
					}
				}
				status {
					publicIpAddress
					privateIpAddress
				}

				users {
					pageInfo {
						hasNextPage
						hasPreviousPage
						totalCount
						pageStart
						pageEnd
						startCursor
						endCursor
					}
					edges {
						node {
							name
							authentication
						}
					}
				}
			}
		}
	}
}
