query SqlInstance($env: String!, $team: Slug!, $name: String!) @loading(cascade: true) {
	sqlInstance(env: $env, team: $team, name: $name) {
		id
		name
		env {
			name
		}
		cascadingDelete
		isHealthy
		type
		connectionName
		workload {
			... on App {
				name
			}
			... on NaisJob {
				name
			}
		}
		tier
		metrics {
			cost
			cpu {
				cores
				utilization
			}
			memory {
				quotaBytes
				utilization
			}
			disk {
				quotaBytes
				utilization
			}
		}
		highAvailability
		backupConfiguration {
			enabled
			startTime
			retainedBackups
			pointInTimeRecovery
		}
		maintenanceWindow {
			day
			hour
		}
		maintenanceVersion
		projectId
		databases {
			name
		}
		flags {
			name
			value
		}
		status {
			conditions {
				type
				status
				reason
				message
				lastTransitionTime
			}
			publicIpAddress
		}
	}
}
