query OpenSearchInstance(
	$environment: String!
	$team: Slug!
	$name: String!
	$orderBy: OpenSearchAccessOrder!
) {
	team(slug: $team) {
		environment(name: $environment) {
			openSearchInstance(name: $name) {
				id
				name
				environment {
					name
				}
				status {
					state
				}
				workload {
					name
					environment {
						name
					}
					__typename
					team {
						slug
					}
				}

				access(first: 10, orderBy: $orderBy) @paginate(mode: SinglePage) {
					pageInfo {
						hasNextPage
						hasPreviousPage
						pageStart
						pageEnd
						totalCount
					}
					edges {
						node {
							access
							workload {
								name
								environment {
									name
								}
								__typename
								team {
									slug
								}
							}
						}
					}
				}
			}
		}
	}
}
