query OpenSearchInstance($env: String!, $team: Slug!, $name: String!) @loading(cascade: true) {
	team(slug: $team) {
		openSearchInstance(env: $env, name: $name) {
			id
			name
			env {
				name
			}
			cost
			status {
				conditions {
					reason
					type
					status
					message
					lastTransitionTime
				}
				state
			}
			workload {
				name
				type
			}
			access {
				workload {
					type
					name
				}
				role
			}
		}
	}
}
