query TeamResourceUsage($team: Slug!) {
	team(slug: $team) @loading {
		memUtil: appsUtilization(resourceType: MEMORY) {
			requested
			used
		}

		cpuUtil: appsUtilization(resourceType: CPU) {
			requested
			used
		}
	}
}
