query TeamIssues(
	$team: Slug!
	$filter: IssueFilter
	$orderBy: IssueOrder
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) @cache(policy: NoCache) {
	team(slug: $team) {
		slug
		issues(
			first: $first
			last: $last
			filter: $filter
			orderBy: $orderBy
			before: $before
			after: $after
		) @paginate(mode: SinglePage) {
			pageInfo {
				startCursor
				endCursor
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
			}
			edges {
				node {
					id
					...IssueFragment @mask_disable
				}
			}
			facets {
				environments {
					value
					count
				}
				severities {
					severity
					count
				}
				issueTypes {
					issueType
					count
				}
			}
		}
	}
}
