query DeleteAppPage($app: String!, $team: Slug!, $env: String!) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		slug
		environment(name: $env) {
			application(name: $app) {
				name
				deletionStartedAt
				teamEnvironment {
					environment {
						name
					}
				}
				team {
					slug
				}
				bigQueryDatasets {
					nodes {
						id
						__typename
						name
						cascadingDelete
					}
				}
				buckets {
					nodes {
						id
						__typename
						name
						cascadingDelete
					}
				}
				redisInstances {
					nodes {
						id
						__typename
						name
					}
				}
				valkeyInstances {
					nodes {
						id
						__typename
						name
					}
				}
				sqlInstances {
					nodes {
						id
						__typename
						name
						cascadingDelete
					}
				}
				openSearch {
					id
					__typename
					name
				}
			}
		}
	}
}
