query Secret($secret: String!, $team: Slug!, $env: String!) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		environment(name: $env) {
			secret(name: $secret) {
				name
				environment {
					name
				}
				#applications {
				#	edges {
				#		node {
				#			name
				#		}
				#	}
				#}
				values {
					name
					value
				}
				#jobs {
				#	edges {
				#		node {
				#			name
				#		}
				#	}
				#}
				workloads {
					nodes {
						__typename
						name
						environment {
							name
						}
						team {
							slug
						}
					}
				}
				lastModifiedAt
				lastModifiedBy {
					name
					email
				}
			}
		}
	}
}
