query KafkaTopics($team: Slug!, $orderBy: KafkaTopicOrder) {
	team(slug: $team) @loading {
		kafkaTopics(first: 20, orderBy: $orderBy) @paginate(mode: SinglePage) @loading {
			pageInfo @loading {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
			}
			nodes @loading {
				name
				environment {
					name
				}
			}
		}
	}
}
