query DeleteJobPage($job: String!, $team: Slug!, $env: String!) @cache(policy: NetworkOnly) {
	naisjob(name: $job, team: $team, env: $env) {
		name
		env {
			name
		}
		team {
			slug
		}
		storage {
			type: __typename
			name
			... on SqlInstance {
				cascadingDelete
			}

			... on BigQueryDataset {
				cascadingDelete
			}

			... on Bucket {
				cascadingDelete
			}
		}
	}
}
