query Secrets($team: Slug!, $orderBy: SecretOrder, $filter: SecretFilter)
@cache(policy: CacheAndNetwork) {
	team(slug: $team) @loading {
		secrets(first: 20, orderBy: $orderBy, filter: $filter) @paginate(mode: SinglePage) @loading {
			pageInfo @loading {
				totalCount
				hasPreviousPage
				hasNextPage
				pageEnd
				pageStart
			}
			nodes @loading {
				name
				lastModifiedAt
				environment {
					name
				}
				workloads {
					pageInfo {
						totalCount
					}
				}
			}
		}
		environments @loading {
			name
		}
	}
}
