query Secrets($team: Slug!, $orderBy: SecretOrder, $filter: SecretFilter)
@cache(policy: CacheAndNetwork) {
	team(slug: $team) {
		secrets(first: 20, orderBy: $orderBy, filter: $filter) @paginate(mode: SinglePage) {
			pageInfo {
				totalCount
				hasPreviousPage
				hasNextPage
				pageEnd
				pageStart
				startCursor
				endCursor
			}
			nodes {
				id
				name
				lastModifiedAt
				environment {
					name
				}
				workloads {
					pageInfo {
						totalCount
					}
				}
			}
		}
		environments {
			name
		}
	}
}
