query Secrets($team: Slug!, $orderBy: SecretOrder) @cache(policy: CacheAndNetwork) {
	team(slug: $team) @loading {
		secrets(first: 20, orderBy: $orderBy) @paginate(mode: SinglePage) @loading {
			pageInfo @loading {
				totalCount
				hasPreviousPage
				hasNextPage
				pageEnd
				pageStart
			}
			nodes @loading {
				name
				lastModifiedAt
				environment {
					name
				}
			}
		}
		environments @loading {
			name
		}
	}
}
