query Redis($team: Slug!, $orderBy: RedisInstanceOrder) {
	team(slug: $team) {
		id
		redisInstances(first: 20, orderBy: $orderBy) @paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				totalCount
				pageStart
				pageEnd
			}

			edges {
				node {
					id
					name
					environment {
						name
					}
					workload {
						name
						__typename
					}
				}
			}
		}
	}
}
