query KafkaTopic($env: String!, $team: Slug!, $name: String!) @loading(cascade: true) {
	kafkaTopic(env: $env, team: $team, name: $name) {
		id
		name
		env {
			name
		}
		config {
			cleanupPolicy
			maxMessageBytes
			minimumInSyncReplicas
			partitions
			retentionBytes
			retentionHours
			segmentHours
		}
		workload {
			... on App {
				name
			}
			... on NaisJob {
				name
			}
		}
		acl @loading(count: 15) {
			application
			access
			team
		}
	}
}
