query KafkaTopic(
	$env: String!
	$team: Slug!
	$name: String!
	$orderBy: OrderBy = { field: APP_NAME, direction: ASC }
	$limit: Int
	$offset: Int
) @loading(cascade: true) {
	team(slug: $team) {
		kafkaTopic(env: $env, name: $name) {
			id
			name
			env {
				name
			}
			config {
				cleanupPolicy
				maxMessageBytes
				minimumInSyncReplicas
				partitions
				retentionBytes
				retentionHours
				segmentHours
			}
			acl(offset: $offset, limit: $limit, orderBy: $orderBy) {
				pageInfo {
					totalCount
					hasNextPage
					hasPreviousPage
				}
				nodes {
					access
					application
					team
				}
			}

			status {
				errors
				fullyQualifiedName
				message
				synchronizationState
				synchronizationTime
				credentialsExpiryTime
				latestAivenSyncFailure
			}
		}
	}
}
