query AppCost($app: String!, $team: Slug!, $env: String!, $from: Date!, $to: Date!)
@cache(policy: NetworkOnly) {
	dailyCostForApp(app: $app, team: $team, env: $env, from: $from, to: $to) {
		series {
			costType
			sum
			data {
				date
				cost
			}
		}
	}
}
