query Workloads($team: Slug!, $orderBy: OrderBy = { field: STATUS, direction: ASC })
@loading(count: 5, cascade: true) {
	team(slug: $team) {
		id
		apps(limit: 50, orderBy: $orderBy) @paginate(mode: SinglePage) {
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
			}

			nodes {
				deployInfo {
					timestamp
				}
				name
				image
				...AppInstancesStatus
				env {
					name
				}

				appState {
					state
				}

				instances {
					state
				}
			}
		}
	}
}
