query JobStatusDetailed($job: String!, $team: Slug!, $env: String!) {
	team(slug: $team) {
		environment(name: $env) {
			job(name: $job) {
				name

				status {
					state
					errors {
						...JobErrorFragment
					}
				}
				runs(first: 20) {
					edges {
						node {
							name
							status {
								state
								message
							}
						}
					}
				}
				networkPolicy {
					inbound {
						rules {
							targetWorkloadName
							targetTeamSlug
							mutual
						}
					}
					outbound {
						rules {
							targetWorkloadName
							targetTeamSlug
							mutual
						}
					}
				}
			}
		}
	}
}
