query AuditEvents($team: Slug!) @cache(policy: NetworkOnly) {
	team(slug: $team) @loading {
		slug
		auditEntries(first: 10) @paginate(mode: SinglePage) @loading {
			pageInfo @loading {
				hasNextPage
				hasPreviousPage
				pageEnd
				pageStart
				totalCount
			}
			edges @loading(count: 10) {
				node @loading {
					__typename
					createdAt @loading
					actor
					createdAt
					environmentName
					message
					resourceName
					resourceType

					... on SecretValueAddedAuditEntry {
						secretValueAdded: data {
							valueName
						}
					}
					... on SecretValueRemovedAuditEntry {
						secretValueRemoved: data {
							valueName
						}
					}
					... on SecretValueUpdatedAuditEntry {
						secretValueUpdated: data {
							valueName
						}
					}
					... on TeamEnvironmentUpdatedAuditEntry {
						teamEnvironmentUpdated: data {
							updatedFields {
								field
								newValue
								oldValue
							}
						}
					}
					... on TeamMemberAddedAuditEntry {
						teamMemberAdded: data {
							role
							userEmail
							userID
						}
					}
					... on TeamMemberRemovedAuditEntry {
						teamMemberRemoved: data {
							userEmail
							userID
						}
					}
					... on TeamMemberSetRoleAuditEntry {
						teamMemberSetRole: data {
							role
							userEmail
							userID
						}
					}
					... on TeamUpdatedAuditEntry {
						teamUpdated: data {
							updatedFields {
								field
								newValue
								oldValue
							}
						}
					}
					... on UnleashInstanceUpdatedAuditEntry {
						unleashInstanceUpdated: data {
							allowedTeamSlug
							revokedTeamSlug
						}
					}
				}
			}
		}
	}
}
