fragment IssueFragment on Issue {
	__typename
	teamEnvironment {
		environment {
			name
		}
		team {
			slug
		}
	}
	message
	severity
	... on DeprecatedIngressIssue {
		application {
			__typename
			name
		}
		ingresses
	}
	... on DeprecatedRegistryIssue {
		workload {
			__typename
			name
			image {
				name
			}
		}
	}
	... on ExternalIngressCriticalVulnerabilityIssue {
		cvssScore
		ingresses
		workload {
			__typename
			name
		}
	}
	... on LastRunFailedIssue {
		job {
			name
		}
	}
	... on InvalidSpecIssue {
		workload {
			__typename
			name
		}
	}
	... on MissingSbomIssue {
		workload {
			__typename
			name
		}
	}
	... on FailedSynchronizationIssue {
		workload {
			__typename
			name
		}
	}
	... on NoRunningInstancesIssue {
		workload {
			__typename
			name
		}
	}
	... on ApplicationRestartLoopIssue {
		workload {
			__typename
			name
		}
	}
	... on OpenSearchIssue {
		event
		openSearch {
			name
		}
	}
	... on SqlInstanceStateIssue {
		sqlInstance {
			name
		}
		state
	}
	... on SqlInstanceVersionIssue {
		sqlInstance {
			name
		}
	}
	... on ValkeyIssue {
		valkey {
			name
		}
	}
	... on VulnerableImageIssue {
		workload {
			__typename
			name
		}
	}
	... on WorkloadProblemIssue {
		workload {
			__typename
			name
		}
	}
	... on UnleashReleaseChannelIssue {
		unleash {
			name
		}
	}
}
