query Secrets($team: Slug!) @cache(policy: CacheAndNetwork) {
	team(slug: $team) @loading {
		environments @loading(count: 2) {
			name @loading
			secrets @loading(count: 4) {
				name
				lastModifiedAt
			}
		}
	}
}
