apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: '{{ .Release.Name }}'
  template:
    metadata:
      annotations:
        prometheus.io/path: '/metrics'
      labels:
        app: '{{ .Release.Name }}'
    spec:
      containers:
        - name: '{{ .Chart.Name }}'
          env:
            - name: 'TENANT_DOMAIN'
              value: '{{ .Values.tenantDomain }}'
            - name: 'TENANT_NAME'
              value: '{{ .Values.fasit.tenant.name }}'
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1069
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          image: '{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Chart.Version }}'
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
            limits:
              memory: 512Mi
