apiVersion: networking.gke.io/v1alpha3
kind: FQDNNetworkPolicy
metadata:
  name: {{ .Release.Name }}-fqdn
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    - fqdns:
      - slack.com
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  policyTypes:
  - Egress
