apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ .Release.Name }}'
  namespace: nais-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  ingressClassName: 'nais-ingress-external'
  rules:
    - host: '{{ .Values.host }}'
      http:
        paths:
          - backend:
              service:
                name: '{{ .Release.Name }}'
                port:
                  number: 80
            path: /
            pathType: Prefix
