apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ .Release.Name }}'
  namespace: nais-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
spec:
  ingressClassName: nais-ingress
  rules:
    - host: '{{ .Values.host }}'
      http:
        paths:
          - backend:
              service:
                name: '{{ .Release.Name }}'
                port:
                  number: 80
            path: /
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ .Release.Name }}-teams-redirect'
  namespace: nais-system
  annotations:
    nginx.ingress.kubernetes.io/temporal-redirect: 'https://{{ .Values.host }}'
spec:
  ingressClassName: nais-ingress
  rules:
    - host: '{{ .Values.teamsHost }}'
      http:
        paths:
          - backend:
              service:
                name: '{{ .Release.Name }}'
                port:
                  number: 80
            path: /
            pathType: Prefix
