apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Release.Name }}"
spec:
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
    - to:
        - podSelector:
            matchLabels:
              app: console-backend
  podSelector:
    matchLabels:
      app: "{{ .Release.Name }}"
  policyTypes:
    - Egress
