apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Release.Name }}'
  labels:
    app: '{{ .Release.Name }}'
type: Opaque
stringData:
  SLACK_FEEDBACK_CHANNEL_ID: '{{ .Values.slack.feedbackChannel }}'
  SLACK_API_TOKEN: '{{ .Values.slack.token }}'
