apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: "{{ .Release.Name }}"
