kind: ServiceAccount
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.serviceaccount.email }}"
  labels:
    app: "{{ .Release.Name }}"
