query JobImageDetails($team: Slug!, $env: String!, $job: String!) {
	team(slug: $team) {
		environment(name: $env) {
			job(name: $job) {
				__typename
				image {
					name
					tag
					hasSBOM

					vulnerabilitySummary {
						critical
						high
						medium
						low
						unassigned
						riskScore
					}

					#vulnerabilities {
					#	edges {
					#		node {
					#			description
					#			identifier
					#			package
					#			severity
					#			state
					#			url
					#		}
					#	}
					#}

					...WorkloadRefs
				}
			}
		}
		viewerIsMember
	}
}
