query KafkaTopic(
	$team: Slug!
	$name: String!
	$environment: String!
	$orderBy: KafkaTopicAclOrder
) {
	team(slug: $team) {
		slug
		environment(name: $environment) {
			kafkaTopic(name: $name) {
				id
				__typename
				name
				teamEnvironment {
					environment {
						name
					}
				}
				configuration {
					cleanupPolicy
					maxMessageBytes
					minimumInSyncReplicas
					partitions
					retentionBytes
					retentionHours
					segmentHours
				}
				acl(first: 10, orderBy: $orderBy) @paginate(mode: SinglePage) {
					pageInfo {
						hasNextPage
						hasPreviousPage
						totalCount
						pageStart
						pageEnd
						startCursor
						endCursor
					}
					nodes {
						access
						workloadName
						teamName
						workload {
							id
							teamEnvironment {
								environment {
									name
								}
							}
							name
							__typename
							team {
								slug
							}
						}
					}
				}
			}
		}
	}
}
