query Secrets(
	$team: Slug!
	$orderBy: SecretOrder
	$filter: SecretFilter
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) @cache(policy: CacheAndNetwork) {
	me {
		... on User {
			isAdmin
		}
	}
	team(slug: $team) {
		viewerIsMember
		secrets(
			first: $first
			last: $last
			before: $before
			after: $after
			orderBy: $orderBy
			filter: $filter
		) @paginate(mode: SinglePage) {
			pageInfo {
				totalCount
				hasPreviousPage
				hasNextPage
				pageEnd
				pageStart
				startCursor
				endCursor
			}
			nodes {
				id
				name
				lastModifiedAt
				teamEnvironment {
					environment {
						name
					}
				}
				workloads {
					pageInfo {
						totalCount
					}
				}
			}
		}
		environments {
			environment {
				name
			}
		}
		...SidebarActivityLogFragment
			@with(
				filter: {
					activityTypes: [
						SECRET_CREATED
						SECRET_VALUE_ADDED
						SECRET_VALUE_UPDATED
						SECRET_VALUE_REMOVED
						SECRET_DELETED
						SECRET_VALUES_VIEWED
					]
				}
			)
			@mask_disable
	}
}
