query JobNotificationState($job: String!, $team: Slug!, $env: String!) @loading(cascade: true) {
	naisjob(name: $job, team: $team, env: $env) {
		jobState {
			state
			errors {
				__typename
			}
		}
	}
}
