query Job($job: String!, $team: Slug!, $env: String!) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		environment(name: $env) {
			job(name: $job) {
				id
				name
				schedule {
					expression
					timeZone
				}
				...JobAuthIntegrations
				...JobInstances
				...JobStatus
				...Persistence
				...WorkloadImage
				...Traffic
				...Manifest
			}
		}
	}

	team(slug: $team) {
		viewerIsOwner
		viewerIsMember
	}
}
