query Job($job: String!, $team: Slug!, $env: String!) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		environment(name: $env) {
			job(name: $job) {
				__typename
				id
				name
				deletionStartedAt
				team {
					slug
				}
				issues {
					edges {
						node {
							id
							...IssueFragment
						}
					}
				}
				schedule {
					expression
					timeZone
				}
				teamEnvironment {
					environment {
						name
					}
				}
				deployments(first: 1) {
					nodes {
						triggerUrl
						statuses {
							nodes {
								state
								message
								createdAt
							}
						}
					}
				}

				...SidebarActivityLogFragment @with(limit: 20) @mask_disable
				...JobRuns
				...Persistence
				...WorkloadDeploy
				...NetworkPolicy
				...Manifest
			}
		}
	}
}
