query Job($job: String!, $team: Slug!, $env: String!) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		environment(name: $env) {
			job(name: $job) {
				__typename
				id
				name
				deletionStartedAt
				team {
					slug
				}
				image {
					hasSBOM
					vulnerabilitySummary {
						critical
						high
						medium
						low
						unassigned
						riskScore
						lastUpdated
					}
				}
				schedule {
					expression
					timeZone
				}
				teamEnvironment {
					environment {
						name
					}
				}
				deployments(first: 1) {
					nodes {
						triggerUrl
						statuses {
							nodes {
								state
								message
								createdAt
							}
						}
					}
				}

				status {
					errors {
						__typename
						level
						... on WorkloadStatusDeprecatedRegistry {
							registry
						}
						... on WorkloadStatusSynchronizationFailing {
							detail
						}
						... on WorkloadStatusInvalidNaisYaml {
							detail
						}
						... on WorkloadStatusFailedRun {
							detail
							name
						}
						... on WorkloadStatusVulnerable {
							summary {
								riskScore
								critical
							}
						}
					}
				}

				...SidebarActivityLogFragment
				...JobRuns
				...Persistence
				...WorkloadDeploy
				...NetworkPolicy
				...Manifest
			}
		}
	}
}
