query AdminUsers {
	users(first: 20) @paginate(mode: SinglePage) {
		nodes {
			name
			email
			externalID
			isAdmin
		}
		pageInfo {
			hasNextPage
			hasPreviousPage
			pageStart
			pageEnd
			totalCount
			startCursor
			endCursor
		}
	}
}
