query AllIssues {
	teams(first: 500) {
		nodes {
			slug
			issues(first: 500) {
				nodes {
					id
					__typename
					teamEnvironment {
						environment {
							name
						}
						team {
							slug
						}
					}
					message
					severity

					... on DeprecatedIngressIssue {
						application {
							name
						}
						ingresses
					}
					... on DeprecatedRegistryIssue {
						workload {
							name
							__typename
						}
					}
					... on FailedJobRunsIssue {
						job {
							name
						}
					}
					... on FailedSynchronizationIssue {
						workload {
							name
						}
					}
					... on MissingSbomIssue {
						workload {
							name
						}
					}
					... on VulnerableImageIssue {
						workload {
							name
						}
					}
					... on InvalidSpecIssue {
						workload {
							name
						}
					}
					... on NoRunningInstancesIssue {
						workload {
							name
						}
					}
					... on OpenSearchIssue {
						event
						openSearch {
							name
						}
					}
					... on SqlInstanceStateIssue {
						sqlInstance {
							name
						}
						state
					}
					... on SqlInstanceVersionIssue {
						sqlInstance {
							name
						}
					}
					... on ValkeyIssue {
						valkey {
							name
						}
					}
				}
			}
		}
	}
}
