query Members(
	$team: Slug!
	$after: Cursor
	$before: Cursor
	$first: Int
	$last: Int
	$orderBy: TeamMemberOrder!
) @blocking {
	team(slug: $team) {
		slug
		members(after: $after, before: $before, first: $first, last: $last, orderBy: $orderBy)
			@paginate(mode: SinglePage) {
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				startCursor
				endCursor
			}
			edges {
				node {
					user {
						id
						email
						name
					}
					role
				}
			}
		}
		...TeamActivityLogFragment
	}
}
