query Members($team: Slug!, $orderBy: TeamMemberOrder!) {
	team(slug: $team) {
		slug
		viewerIsOwner
		members(first: 20, orderBy: $orderBy) @paginate(mode: SinglePage) {
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				startCursor
				endCursor
			}
			edges {
				node {
					user {
						id
						email
						name
					}

					role
				}
			}
		}
	}
}
