query JobCost($job: String!, $team: String!, $env: String!, $from: Date, $to: Date) {
	cost(filter: { app: $job, team: $team, env: $env, from: $from, to: $to }) {
		from
		to
		series {
			costType
			app
			env
			team
			sum
			data {
				date
				cost
			}
		}
	}
}
