query TeamSettings($team: Slug!) {
	team(slug: $team) @loading {
		id @loading
		slug
		purpose
		slackChannel @loading
		gitHubTeamSlug
		azureGroupID
		googleGroupEmail
		googleArtifactRegistry
		environments @loading(count: 2) {
			name
			namespace
			gcpProjectID
			slackAlertsChannel
		}
		# Default limit is 20, should be enough
		# gcpProjects: reconcilerResources(reconciler: "google:gcp:project", key: "project") {
		# 	nodes {
		# 		value
		# 	}
		# }
		# azureADGroupId: reconcilerResources(reconciler: "azure:group", key: "groupID", limit: 1) {
		# 	nodes {
		# 		value
		# 	}
		# }
		# garRepositoryName: reconcilerResources(
		# 	reconciler: "google:gcp:gar"
		# 	key: "repository_name"
		# 	limit: 1
		# ) {
		# 	nodes {
		# 		value
		# 	}
		# }
		# gitHubTeamSlug: reconcilerResources(reconciler: "github:team", key: "slug", limit: 1) {
		# 	nodes {
		# 		value
		# 	}
		# }
		# naisNamespaces: reconcilerResources(reconciler: "nais:namespace", key: "namespace") {
		# 	nodes {
		# 		value
		# 	}
		# }
		# gitHubRepositories(limit: 10) {
		# 	nodes {
		# 		name
		# 	}
		# 	pageInfo {
		# 		totalCount
		# 		hasNextPage
		# 		hasPreviousPage
		# 	}
		# }
	}
}
