query TeamSettings($team: String!) @loading(cascade: true) {
	team(name: $team) {
		id
		name
		slackAlertsChannels {
			env
			name
		}
		gcpProjects {
			id
			environment
		}
		githubRepositories {
			edges {
				node {
					name
				}
			}
		}
		slackChannel
		description
	}
}
