query TeamSettings($team: Slug!) {
	team(slug: $team) @loading {
		id @loading
		slug
		purpose
		slackChannel @loading
		slackAlertsChannels @loading(count: 2) {
			channelName
			environment
		}
		reconcilerState {
			gcpProjects {
				projectId
				environment
			}
			azureADGroupId
			garRepositoryName
			gitHubTeamSlug
			googleWorkspaceGroupEmail
			naisNamespaces {
				environment
				namespace
			}
		}
		gitHubRepositories(limit: 10) {
			nodes {
				name
			}
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
			}
		}
	}
}
