query Overview($team: String!) @cache(policy: NetworkOnly) {
	currentResourceUtilizationForTeam(team: $team) @loading {
		cpu {
			utilization
			estimatedAnnualOverageCost
		}
		memory {
			utilization
			estimatedAnnualOverageCost
		}
	}
	resourceUtilizationTrendForTeam(team: $team) @loading {
		cpuUtilizationTrend
		memoryUtilizationTrend
	}
}
