query Workloads($team: String!) {
	team(name: $team) {
		name
		apps {
			edges {
				node {
					name
					image
					...AppInstancesStatus
					env {
						name
					}
					deployed
				}
			}
		}
	}
}
