query Workloads($team: String!) @loading(count: 5, cascade: true) {
	team(name: $team) {
		id
		apps(first: 50) @paginate(mode: SinglePage) {
			totalCount
			pageInfo {
				hasNextPage
				hasPreviousPage
				startCursor
				endCursor
				from
				to
			}

			edges {
				node {
					deployInfo {
						timestamp
					}
					name
					image
					...AppInstancesStatus
					env {
						name
					}

					appState {
						state
					}

					instances {
						state
					}
				}
			}
		}
	}
}
