query OpenSearch(
	$team: Slug!
	$orderBy: OpenSearchOrder
	$filter: OpenSearchFilter
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) @cache(policy: CacheAndNetwork) {
	team(slug: $team) {
		slug

		openSearches(
			first: $first
			last: $last
			orderBy: $orderBy
			filter: $filter
			before: $before
			after: $after
		) @paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				totalCount
				pageStart
				pageEnd
				startCursor
				endCursor
			}
			facets {
				environments {
					value
					count
				}
				tiers {
					tier
					count
				}
				labels {
					key
					value
					count
				}
			}
			edges {
				node {
					id
					__typename
					name
					teamEnvironment {
						environment {
							name
						}
					}
					team {
						slug
					}
					state
					issues {
						pageInfo {
							totalCount
						}
						edges {
							node {
								severity
							}
						}
					}
				}
			}
		}
	}
}
