query OpenSearch(
	$team: Slug!
	$orderBy: OpenSearchOrder
	$from: Date!
	$to: Date!
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) @cache(policy: CacheAndNetwork) {
	team(slug: $team) {
		slug

		cost {
			daily(from: $from, to: $to, filter: { services: ["OpenSearch"] }) {
				series {
					services {
						service
					}
					date
					sum
				}
			}
		}

		openSearches(first: $first, last: $last, orderBy: $orderBy, before: $before, after: $after)
			@paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				totalCount
				pageStart
				pageEnd
				startCursor
				endCursor
			}
			nodes {
				id
				__typename
				name
				teamEnvironment {
					environment {
						name
					}
				}
				team {
					slug
				}
				workload {
					__typename
					name
					teamEnvironment {
						environment {
							name
						}
					}
					team {
						slug
					}
				}
			}
		}
	}
}
