query JobDeploys($job: String!, $team: String!, $env: String!) @loading {
	naisjob(name: $job, team: $team, env: $env) {
		name @loading
		deployInfo {
			history {
				... on DeploymentList {
					nodes @loading(count: 5) {
						id
						resources {
							group
							kind
							name
							version
						}
						statuses {
							status
							message
							created
						}
						created
						repository
					}
				}
				... on Error {
					message
				}
			}
		}
	}
}
