query Jobs($team: Slug!, $orderBy: JobOrder, $filter: TeamJobsFilter) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		environments {
			name
		}
		jobs(first: 20, orderBy: $orderBy, filter: $filter) @paginate(mode: SinglePage) {
			pageInfo {
				totalCount
				endCursor
				startCursor
				hasNextPage
				hasPreviousPage
				pageEnd
				pageStart
			}
			nodes {
				name
				environment {
					name
				}
				runs(first: 1) {
					nodes {
						startTime
						status {
							state
						}
					}
				}
				status {
					state
				}
				deploymentInfo {
					timestamp
				}
			}
		}
	}
}
