query Jobs($team: Slug!, $orderBy: JobOrder, $filter: TeamJobsFilter) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		id
		jobs(first: 20, orderBy: $orderBy, filter: $filter) @paginate(mode: SinglePage) {
			pageInfo {
				totalCount
				endCursor
				startCursor
				hasNextPage
				hasPreviousPage
				pageEnd
				pageStart
			}
			edges {
				node {
					id
					name
					environment {
						name
					}
					status {
						state
					}

					deploymentInfo {
						timestamp
					}
				}
			}
		}
	}
}
