query Jobs($team: Slug!, $orderBy: JobOrder, $filter: TeamJobsFilter) @cache(policy: NetworkOnly) {
	team(slug: $team) @loading {
		jobs(first: 20, orderBy: $orderBy, filter: $filter) @paginate(mode: SinglePage) @loading {
			pageInfo @loading {
				totalCount
				endCursor
				startCursor
				hasNextPage
				hasPreviousPage
				pageEnd
				pageStart
			}
			nodes @loading(count: 20) {
				name
				environment {
					name
				}
				status {
					state
				}
				deploymentInfo {
					timestamp
				}
			}
		}
	}
}
