query TenantVulnerabilites(
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
	$orderBy: TeamOrder
	$mostVulnerableTeamsField: TeamOrderField!
	$mostVulnerableTeamsDirection: OrderDirection!
) @blocking {
	teams(first: $first, last: $last, before: $before, after: $after, orderBy: $orderBy)
		@paginate(mode: SinglePage) {
		pageInfo {
			endCursor
			hasNextPage
			hasPreviousPage
			pageEnd
			pageStart
			startCursor
			totalCount
		}
		nodes {
			slug
			workloads {
				pageInfo {
					totalCount
				}
			}
			vulnerabilitySummary {
				critical
				high
				medium
				low
				unassigned
				riskScore
				coverage
			}
		}
	}
	mostVulnerableTeams: teams(
		first: 20
		orderBy: { field: $mostVulnerableTeamsField, direction: $mostVulnerableTeamsDirection }
	) {
		nodes {
			slug
			workloads {
				pageInfo {
					totalCount
				}
			}
			vulnerabilitySummary {
				riskScore
				critical
				high
				medium
				low
				unassigned
				coverage
			}
		}
	}
}
