query TenantVulnerabilites($from: Date!) @blocking {
	teams(first: 999) {
		pageInfo {
			endCursor
			hasNextPage
			hasPreviousPage
			pageEnd
			pageStart
			startCursor
			totalCount
		}
		nodes {
			slug
			vulnerabilitySummary {
				critical
				high
				medium
				low
				unassigned
				riskScore
				bomCount
			}
			workloads {
				pageInfo {
					totalCount
				}
			}
		}
	}
	imageVulnerabilityHistory(from: $from) {
		samples {
			date
			summary {
				critical
				high
				low
				medium
				unassigned
			}
		}
	}
}
