query TenantVulnerabilites($from: Date!) @cache(policy: NetworkOnly) {
	imageVulnerabilityHistory(from: $from) {
		samples {
			date
			summary {
				critical
				high
				low
				medium
				unassigned
			}
		}
	}
}
