query TenantVulnerabilites(
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
	$orderBy: TeamOrder
) {
	teams(
		first: $first
		last: $last
		before: $before
		after: $after
		orderBy: $orderBy
		filter: { hasWorkloads: true }
	) @paginate(mode: SinglePage) {
		pageInfo {
			endCursor
			hasNextPage
			hasPreviousPage
			pageEnd
			pageStart
			startCursor
			totalCount
		}
		nodes {
			slug
			workloads {
				pageInfo {
					totalCount
				}
			}
			vulnerabilitySummary {
				critical
				high
				medium
				low
				unassigned
				riskScore
				coverage
			}
		}
	}
	vulnerabilitySummary {
		critical
		high
		medium
		low
		unassigned
		riskScore
		coverage
		sbomCount
	}
}
