query Images(
	$team: Slug!
	$orderBy: OrderBy = { field: NAME, direction: ASC }
	$limit: Int
	$offset: Int
) {
	team(slug: $team) {
		id
		images(limit: $limit, offset: $offset, orderBy: $orderBy) {
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
			}
			nodes {
				id
				projectId
				name
				version
				digest
				rekorId
				critical
				riskScore
				findings {
					id
					description
					componentId
					cveId
					ghsaId
					osvId
					severity
					packageUrl
					vulnerabilityId
				}
				workloadReferences {
					id
					name
					team
					workloadType
					environment
				}
			}
		}
	}
}
