query Images(
	$team: Slug!
	$orderBy: OrderBy = { field: NAME, direction: ASC }
	$limit: Int
	$offset: Int
) @loading(cascade: false) {
	team(slug: $team) {
		id @loading
		images(limit: $limit, offset: $offset, orderBy: $orderBy) {
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
			}
			nodes @loading(count: 18, cascade: false) {
				id @loading
				name
				projectId
				version
				summary {
					critical
					riskScore
				}
				workloadReferences {
					id
					name
					team
					workloadType
					environment
				}
			}
		}
	}
}
