query TeamAuditLogs($team: Slug!, $limit: Int, $offset: Int) {
	team(slug: $team) @loading {
		auditLogs(limit: $limit, offset: $offset) @loading {
			nodes @loading(count: 15) {
				actor
				message
				createdAt
			}
			pageInfo @loading {
				hasNextPage @loading
				totalCount @loading
			}
		}
	}
}
