query PostgresInstance($env: String!, $team: Slug!, $name: String!) {
	team(slug: $team) {
		slug
		environment(name: $env) {
			postgresInstance(name: $name) {
				id
				name
				workloads(first: 50) {
					pageInfo {
						totalCount
					}
					nodes {
						id
						name
						__typename
						team {
							slug
						}
						teamEnvironment {
							environment {
								name
							}
						}
					}
				}
				teamEnvironment {
					environment {
						name
					}
				}
				audit {
					enabled
					url
					statementClasses
				}
				highAvailability
				state
				maintenanceWindow {
					day
					hour
				}
				majorVersion
				resources {
					cpu
					memory
					diskSize
				}
			}
		}
	}
}
