query PostgresInstance($env: String!, $team: Slug!, $name: String!) {
	team(slug: $team) {
		slug
		environment(name: $env) {
			postgresInstance(name: $name) {
				__typename
				id
				name
				teamEnvironment {
					environment {
						name
					}
				}
				majorVersion
				resources {
					cpu
					memory
					diskSize
				}
			}
		}
	}
}
