query Deployments($team: Slug!, $first: Int, $last: Int, $before: Cursor, $after: Cursor) {
	team(slug: $team) {
		deployments(first: $first, last: $last, before: $before, after: $after)
			@paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				endCursor
				hasPreviousPage
				pageEnd
				pageStart
				startCursor
				totalCount
			}
			nodes {
				id
				statuses {
					nodes {
						state
						message
						createdAt
					}
				}
				resources {
					nodes {
						id
						kind
						name
					}
				}
				environmentName
				createdAt
				teamSlug
				repository
				commitSha
				deployerUsername
				triggerUrl
			}
		}
	}
}
