query Deploys {
	deployments(first: 10) @paginate(mode: SinglePage) @loading {
		totalCount
		pageInfo @loading {
			hasNextPage
			hasPreviousPage
			startCursor
			endCursor
			from
			to
		}
		edges @loading(count: 10) {
			node @loading {
				id @loading
				team {
					name
				}
				repository
				resources {
					group
					kind
					name
					version
					namespace
				}
				env
				statuses {
					status
					message
					created
				}
				created
			}
		}
	}
}
