query Deploys {
	deployments(first: 10) @paginate(mode: SinglePage) @loading(cascade: true) {
		totalCount
		pageInfo {
			hasNextPage
			hasPreviousPage
			startCursor
			endCursor
			from
			to
		}
		edges @loading(count: 10) {
			node {
				id
				team {
					name
				}
				repository
				resources {
					group
					kind
					name
					version
					namespace
				}
				env
				statuses {
					status
					message
					created
				}
				created
			}
		}
	}
}
