query Repositories(
	$team: Slug!
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
	$orderBy: RepositoryOrder
	$filter: TeamRepositoryFilter
) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		userIsMember
		userIsOwner
		repositories(
			first: $first
			last: $last
			before: $before
			after: $after
			orderBy: $orderBy
			filter: $filter
		) @paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
				startCursor
				endCursor
			}
			nodes {
				id
				name
				team {
					slug
				}
			}
		}
		...SidebarActivityLogFragment
			@with(filter: { activityTypes: [REPOSITORY_ADDED, REPOSITORY_REMOVED] })
			@mask_disable
	}
}
