query TenantCost($from: Date!, $to: Date!) {
	teams(first: 5) {
		nodes {
			slug
			cost {
				daily(from: $from, to: $to) {
					series {
						services {
							cost
							service
						}
						date
						sum
					}
				}
			}
		}
	}
}
