query TenantCost($first: Int, $last: Int, $before: Cursor, $after: Cursor, $orderBy: TeamOrder) {
	teams(first: $first, last: $last, before: $before, after: $after, orderBy: $orderBy)
		@paginate(mode: SinglePage) {
		pageInfo {
			endCursor
			hasNextPage
			hasPreviousPage
			pageEnd
			pageStart
			startCursor
			totalCount
		}
		nodes {
			slug
			cost {
				monthlySummary {
					sum
				}
			}
		}
	}
}
