environmentKinds:
  - management
values:
  host:
    displayName: hostname override
    computed:
      template: '{{ subdomain . "console" }}'
    config:
      type: string
  tenantDomain:
    computed:
      template: '{{ subdomain . "" }}'
