environmentKinds:
  - management
values:
  host:
    displayName: override hostname during testing
    computed:
      template: '{{ subdomain . "console" }}'
    config:
      type: string
  teamsHost:
    displayName: host for the old teams frontend, used to set up redirect
    computed:
      template: '{{ subdomain . "teams" }}'
    config:
      type: string
  tenantDomain:
    computed:
      template: '{{ subdomain . "" }}'
  slack.token:
    displayName: Slack token
    description: Token for the Slack API
    config:
      type: string
      secret: true
  slack.feedbackChannel:
    displayName: Slack feedback channel
    description: The Slack channel to post feedback to
    config:
      type: string
  gitHub.organization:
    displayName: GitHub organization
    description: The organization slug where the github reconciler will manage teams
    computed:
      template: |
        {{ .Env.teams_github_org | quote }}
