environmentKinds:
  - management
values:
  host:
    displayName: hostname override
    computed:
      template: '{{ subdomain . "console" }}'
    config:
      type: string
  tenantDomain:
    computed:
      template: '{{ subdomain . "" }}'
  slack.token:
    displayName: Slack token
    description: Token for the Slack API
    config:
      type: string
      secret: true
  slack.feedbackChannel:
    displayName: Slack feedback channel
    description: The Slack channel to post feedback to
    config:
      type: string
  gitHub.organization:
    displayName: GitHub organization
    description: The organization slug where the github reconciler will manage teams
    computed:
      template: |
        {{ .Env.teams_github_org | quote }}
  resources.requests.cpu:
    displayName: CPU requests
    config:
      type: string
  resources.requests.memory:
    displayName: Memory requests
    config:
      type: string
  resources.limits.memory:
    displayName: Memory limits
    config:
      type: string
