query RedisInstance($env: String!, $team: Slug!, $name: String!) @loading(cascade: true) {
	team(slug: $team) {
		redisInstance(env: $env, name: $name) {
			id
			name
			access {
				workload {
					type: __typename
					... on App {
						name
					}
				}
				role
			}
			env {
				name
			}
			workload {
				... on App {
					name
				}
				... on NaisJob {
					name
				}
			}
		}
	}
}
