query RedisInstance(
	$environment: String!
	$team: Slug!
	$name: String!
	$orderBy: RedisInstanceAccessOrder!
) {
	team(slug: $team) {
		environment(name: $environment) {
			redisInstance(name: $name) {
				id
				name
				environment {
					name
				}
				status {
					state
				}
				workload {
					name
					__typename
				}
				access(first: 10, orderBy: $orderBy) @paginate(mode: SinglePage) {
					pageInfo {
						hasNextPage
						hasPreviousPage
						pageStart
						pageEnd
						totalCount
					}

					edges {
						node {
							access
							workload {
								name
								environment {
									name
								}
								__typename
							}
						}
					}
				}
			}
		}
	}
}
