query TeamResourceUsage {
	team(slug: "devteam") @loading {
		memUtil: appsUtilization(resourceType: MEMORY) {
			name
			env
			requested
			used
		}

		cpuUtil: appsUtilization(resourceType: CPU) {
			name
			env
			requested
			used
		}
	}
}
