query TeamResourceUsage {
	team(slug: "devteam") @loading {
		memUtil: appUtilization(resourceType: MEMORY) {
			name
			env
			requested
			used
		}

		cpuUtil: appUtilization(resourceType: CPU) {
			name
			env
			requested
			used
		}
	}
}
