query TeamResourceUsage {
	team(slug: "devteam") @loading {
		memUtil: appsUtilization(resourceType: MEMORY) {
			app {
				name
				env {
					name
				}
			}
			requested
			used
		}

		cpuUtil: appsUtilization(resourceType: CPU) {
			app {
				name
				env {
					name
				}
			}
			requested
			used
		}
	}
}
