query CVES($first: Int, $last: Int, $before: Cursor, $after: Cursor, $orderBy: CVEOrder) {
	cves(first: $first, last: $last, before: $before, after: $after, orderBy: $orderBy)
		@paginate(mode: SinglePage) {
		pageInfo {
			endCursor
			hasNextPage
			hasPreviousPage
			pageEnd
			pageStart
			startCursor
			totalCount
		}
		nodes {
			id
			identifier
			severity
			title
			description
			detailsLink
			cvssScore
			workloads {
				pageInfo {
					totalCount
				}
			}
		}
	}
}
