query TeamVulnerabilities($team: Slug!, $filter: TeamVulnerabilitySummaryFilter)
@cache(policy: CacheAndNetwork) {
	team(slug: $team) {
		environments {
			id
			environment {
				name
			}
		}
		vulnerabilitySummary(filter: $filter) {
			bomCount
			coverage
			critical
			high
			low
			medium
			ranking
			riskScore
			riskScoreTrend
			unassigned
			status {
				state
				title
				description
			}
		}
		workloads {
			pageInfo {
				totalCount
			}
			nodes {
				__typename
				name
				teamEnvironment {
					environment {
						name
					}
				}
				team {
					slug
				}
				status {
					errors {
						__typename
						level
						... on WorkloadStatusVulnerable {
							summary {
								riskScore
								critical
							}
						}
						... on WorkloadStatusMissingSBOM {
							level
						}
					}
				}
			}
		}
	}
}
