query TeamVulnerabilities($team: Slug!) @cache(policy: CacheAndNetwork) {
	team(slug: $team) {
		environments {
			id
			environment {
				name
			}
		}

		workloads(first: 999) {
			pageInfo {
				totalCount
			}
			nodes {
				__typename
				name
				teamEnvironment {
					environment {
						name
					}
				}
				team {
					slug
				}
				# status {
				# 	errors {
				# 		__typename
				# 		level
				# 		... on WorkloadStatusVulnerable {
				# 			summary {
				# 				riskScore
				# 				critical
				# 			}
				# 		}
				# 		... on WorkloadStatusMissingSBOM {
				# 			level
				# 		}
				# 	}
				# }
			}
		}
		...VulnerabilityOverviewFragment
	}
}
