query TeamVulnerabilities($team: Slug!, $from: Date!) @cache(policy: CacheAndNetwork) {
	team(slug: $team) {
		environments {
			id
			environment {
				name
			}
		}
		imageVulnerabilityHistory(from: $from) {
			samples {
				date
				summary {
					critical
					high
					low
					medium
					unassigned
				}
			}
		}

		workloads(first: 999) {
			pageInfo {
				totalCount
			}
			nodes {
				__typename
				name
				teamEnvironment {
					environment {
						name
					}
				}
				team {
					slug
				}
			}
		}
		...VulnerabilityOverviewFragment
	}
}
