query TeamVulnerabilities($team: Slug!) @cache(policy: CacheAndNetwork) {
	team(slug: $team) {
		environments {
			id
			environment {
				name
			}
		}
		workloads {
			pageInfo {
				totalCount
			}
		}

		vulnerabilitySummary {
			sbomCount
			coverage
			critical
			riskScore
			riskScoreTrend
			lastUpdated
		}
	}
}
