query TeamVulnerabilities($team: Slug!) {
	team(slug: $team) {
		environments {
			id
			environment {
				name
			}
		}
		workloads {
			pageInfo {
				totalCount
			}
		}

		vulnerabilitySummary {
			sbomCount
			coverage
			highWorkloadCount
			elevatedWorkloadCount
			monitorWorkloadCount
			countsByPriority {
				knownExploited
				highRisk
				elevatedRisk
				monitor
			}
			critical
			high
			medium
			low
			unassigned
			lastUpdated
		}
	}
}
