query TeamCost($team: String!, $from: Date, $to: Date) {
	cost(filter: { app: "", team: $team, env: "", from: $from, to: $to }) {
		from
		to
		series {
			costType
			app
			env
			team
			sum
			data {
				date
				cost
			}
		}
	}
}
