query AppDeploys($app: String!, $team: String!, $env: String!) @loading {
	app(name: $app, team: $team, env: $env) {
		name @loading
		deployInfo {
			history {
				... on DeploymentConnection {
					edges @loading(count: 2) {
						node {
							id
							resources {
								group
								kind
								name
								version
							}
							statuses {
								status
								message
								created
							}
							created
							repository
						}
					}
				}
				... on Error {
					message
				}
			}
		}
	}
}
