query TeamCVEWorkloadsCount($identifier: String!, $filter: CVEWorkloadsFilter)
@cache(policy: CacheAndNetwork) {
	cve(identifier: $identifier) {
		id
		workloads(filter: $filter) {
			pageInfo {
				totalCount
			}
		}
	}
}
