query TeamCVEPage($identifier: String!, $team: Slug!) {
	cve(identifier: $identifier) {
		id
		identifier
		title
		description
		severity
		cvssScore
		detailsLink
		hasKevEntry
		knownRansomwareUse
		epssScore
		epssPercentile
	}
	team(slug: $team) {
		viewerIsMember
	}
}
