query AllIngresses {
	teams(first: 500) {
		nodes {
			slug
			workloads(first: 500) {
				nodes {
					__typename
					id
					name
					team {
						slug
					}
					teamEnvironment {
						environment {
							name
						}
					}

					... on Application {
						instances {
							nodes {
								id
								name
								status {
									state
									message
								}
							}
						}
					}

					... on Job {
						runs {
							nodes {
								id
								name
								status {
									state
									message
								}
							}
						}
					}

					status {
						errors {
							level
							... on WorkloadStatusDeprecatedIngress {
								ingress
							}
							... on WorkloadStatusSynchronizationFailing {
								detail
							}
							... on WorkloadStatusFailedRun {
								detail
								name
							}
							... on WorkloadStatusInvalidNaisYaml {
								detail
							}
							... on WorkloadStatusFailedRun {
								detail
								name
							}
						}
					}
				}
			}
		}
	}
}
