query Image(
	$dependencyTrackProjectId: String!
	$orderBy: OrderBy = { field: SEVERITY, direction: DESC }
	$limit: Int
	$offset: Int
) {
	dependencyTrackProject(projectId: $dependencyTrackProjectId) {
		id
		projectId
		version
		name
		digest
		rekorId
		summary {
			critical
			high
			medium
			low
			unassigned
			riskScore
		}
		workloadReferences {
			id
			name
			team
			workloadType
			environment
		}
		findings(limit: $limit, offset: $offset, orderBy: $orderBy) {
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
			}
			nodes {
				componentId
				cveId
				description
				ghsaId
				id
				osvId
				packageUrl
				severity
				vulnerabilityId
			}
		}
	}
}
