query Image($dependencyTrackProjectId: String!) {
	dependencyTrackProject(projectId: $dependencyTrackProjectId) @loading {
		id @loading
		name
		digest
		rekorId
		critical
		riskScore
		findings {
			id
			componentId
			cveId
			ghsaId
			osvId
			description
			severity
			packageUrl
			vulnerabilityId
		}
	}
}
