/**
 * Re-exports of the fragment-masking helpers generated by GraphQL Code
 * Generator's `client` preset.
 *
 * Use {@link useFragment} (or its {@link getFragmentData} alias) to
 * unwrap a masked fragment value:
 *
 * ```ts
 * import { useFragment, type FragmentType } from '$lib/urql/fragment';
 * import { SidebarActivityLogFragment } from './SidebarActivity';
 *
 * let { data }: { data: FragmentType<typeof SidebarActivityLogFragment> } = $props();
 * const unmasked = $derived(useFragment(SidebarActivityLogFragment, data));
 * ```
 *
 * Use `FragmentType<typeof SomeFragment>` for prop typing, and
 * `useFragment` (or {@link getFragmentData}) to read the fragment's
 * data at runtime.
 */
export {
	useFragment as getFragmentData,
	isFragmentReady,
	makeFragmentData,
	useFragment,
	type FragmentType
} from './gql/fragment-masking';
