query AdminServiceAccountDetail($id: ID!) @cache(policy: CacheAndNetwork) {
	serviceAccount(id: $id) {
		id
		name
		description
		createdAt
		updatedAt
		lastUsedAt
		...ServiceAccountRolesFragment
		...ServiceAccountAuthenticationFragment @mask_disable
	}
	roles(first: 100, filter: { excludeGlobalRoles: false }) {
		edges {
			node {
				name
				description
			}
		}
	}
}
