query AppStatusDetailed($app: String!, $team: String!, $env: String!) {
	app(name: $app, team: $team, env: $env) @loading(cascade: true) {
		name @loading

		appState @loading {
			state

			errors {
				...AppErrorFragment
			}
		}
		instances {
			name
			state
			message
		}
		accessPolicy {
			inbound {
				rules {
					application
					namespace
					cluster
					mutual
				}
			}
			outbound {
				rules {
					application
					namespace
					cluster
					mutual
				}
			}
		}
	}
}
