query TeamVulnerabilities(
	$limit: Int
	$offset: Int
	$team: Slug!
	$orderBy: OrderBy = { field: SEVERITY_CRITICAL, direction: DESC }
	$filter: VulnerabilityFilter
) {
	team(slug: $team) @loading {
		id @loading
		slug
		environments {
			name
		}
		vulnerabilities(limit: $limit, offset: $offset, orderBy: $orderBy, filter: $filter) @loading {
			pageInfo @loading {
				totalCount
				hasNextPage
				hasPreviousPage
			}

			nodes @loading(count: 10) {
				workloadName
				workloadType
				env
				hasBom
				summary {
					riskScore
					unassigned
					critical
					high
					medium
					low
				}
			}
		}
		vulnerabilitiesSummary {
			riskScore
			critical
			high
			medium
			low
			bomCount
			unassigned
			coverage
			totalWorkloads
		}
	}
}
