query AddBindingSALookup($team: Slug!, $after: Cursor) @cache(policy: CacheAndNetwork) {
	team(slug: $team) {
		serviceAccounts(first: 50, after: $after) {
			pageInfo {
				hasNextPage
				endCursor
			}
			nodes {
				id
				name
				workloadBindings(first: 100) {
					edges {
						node {
							workloadName
							environment
						}
					}
				}
			}
		}
	}
}
