query AllImages {
	teams(first: 500) {
		nodes {
			slug
			workloads(first: 1000) {
				nodes {
					__typename
					id
					name
					team {
						slug
					}
					teamEnvironment {
						environment {
							name
						}
					}
					image {
						hasSBOM
						vulnerabilitySummary {
							riskScore
						}
					}

					status {
						errors {
							... on WorkloadStatusDeprecatedRegistry {
								name
								registry
								repository
								tag
							}
						}
					}
				}
			}
		}
	}
}
