query AppCost($app: String!, $team: Slug!, $env: String!, $from: Date!, $to: Date!)
@cache(policy: NetworkOnly) {
	team(slug: $team) @loading {
		environment(name: $env) @loading {
			application(name: $app) @loading {
				cost @loading {
					daily(from: $from, to: $to) @loading {
						series {
							date
							services {
								cost
								service
							}
							sum
						}
					}
				}
			}
		}
	}
}
