query JobActivityLog(
	$team: Slug!
	$env: String!
	$job: String!
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
	$filter: ActivityLogFilter
) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		environment(name: $env) {
			job(name: $job) {
				id
				name
				activityLog(first: $first, last: $last, before: $before, after: $after, filter: $filter)
					@paginate(mode: SinglePage) {
					pageInfo {
						hasNextPage
						hasPreviousPage
						pageEnd
						pageStart
						totalCount
						startCursor
						endCursor
					}
					nodes {
						...ActivityLogEntryFragment
					}
					facets {
						activityTypes {
							activityType
							count
						}
						resourceTypes {
							resourceType
							count
						}
						environments {
							value
							count
						}
					}
				}
			}
		}
	}
}
