# If you update this query, remember to update the corresponding mutation when creating a new Unleash instance
query Unleash($team: Slug!) {
	team(slug: $team) {
		unleash {
			enabled
			instance {
				name
				version
				allowedTeams
				webIngress
				apiIngress
				metrics {
					apiTokens
					cpuUtilization
					cpuRequests
					memoryUtilization
					memoryRequests
					toggles
				}
				ready
			}
		}
	}
}
