query TeamDeployments($team: String!) @loading(cascade: true) {
	team(name: $team) {
		deployments(first: 10) @paginate(mode: SinglePage) {
			totalCount
			pageInfo {
				hasNextPage
				hasPreviousPage
				from
				to
			}
			edges @loading(count: 10) {
				node {
					id
					created
					env
					repository
					resources {
						group
						kind
						version
						name
						namespace
					}
					statuses {
						created
						message
						status
					}
				}
			}
		}
	}
}
