query UpdateOpenSearchData($environment: String!, $team: Slug!, $name: String!)
@cache(policy: NetworkOnly) {
	team(slug: $team) {
		slug
		environment(name: $environment) {
			openSearch(name: $name) {
				tier
				size
				version {
					desiredMajor
				}
			}
		}
	}
}
