query AdminUsers($limit: Int, $offset: Int) {
	users(limit: $limit, offset: $offset) {
		nodes {
			name
			email
			externalId
			isAdmin
		}
		pageInfo {
			totalCount
			hasNextPage
			hasPreviousPage
		}
	}
}
