query Valkey($environment: String!, $team: Slug!, $name: String!, $orderBy: ValkeyAccessOrder!)
@cache(policy: CacheAndNetwork) {
	team(slug: $team) {
		slug
		environment(name: $environment) {
			environment {
				name
			}
			valkey(name: $name) {
				__typename
				id
				name
				tier
				memory
				maxMemoryPolicy
				notifyKeyspaceEvents
				state
				teamEnvironment {
					environment {
						name
					}
				}
				issues {
					edges {
						node {
							id
							...IssueFragment
						}
					}
				}
				maintenance {
					window {
						dayOfWeek
						timeOfDay
					}
					updates {
						pageInfo {
							hasNextPage
							hasPreviousPage
							pageStart
							pageEnd
							totalCount
							startCursor
							endCursor
						}
						nodes {
							deadline
							description
							startAt
							title
						}
					}
				}

				access(first: 10, orderBy: $orderBy) @paginate(mode: SinglePage) {
					pageInfo {
						hasNextPage
						hasPreviousPage
						pageStart
						pageEnd
						totalCount
						startCursor
						endCursor
					}

					edges {
						node {
							access
							workload {
								id
								name
								teamEnvironment {
									environment {
										name
									}
								}
								__typename
								team {
									slug
								}
							}
						}
					}
				}

				...ValkeyManifestFragment
			}
		}
	}
}
