query ReconcilerLogs {
	reconcilers {
		nodes {
			enabled
			displayName
			name
			description
			errors(first: 10) {
				nodes {
					correlationID
					createdAt
					message
					team {
						slug
					}
				}
			}
		}
	}
}
