query Buckets(
	$team: Slug!
	$orderBy: BucketOrder
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
	$from: Date!
	$to: Date!
) @blocking {
	team(slug: $team) {
		slug
		cost {
			daily(from: $from, to: $to, filter: { services: ["Cloud Storage"] }) {
				series {
					date
					sum
				}
			}
		}

		buckets(first: $first, last: $last, orderBy: $orderBy, before: $before, after: $after)
			@paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
				startCursor
				endCursor
			}
			nodes {
				id
				__typename
				name
				teamEnvironment {
					environment {
						name
					}
				}
				team {
					slug
				}
				workload {
					__typename
					name
					teamEnvironment {
						environment {
							name
						}
					}
					team {
						slug
					}
				}
			}
		}

		externalResources {
			cdn {
				bucket
			}
		}
	}
}
