query Buckets(
	$team: Slug!
	$orderBy: BucketOrder
	$filter: BucketFilter
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) @cache(policy: CacheAndNetwork, partial: true) {
	team(slug: $team) {
		slug

		buckets(
			first: $first
			last: $last
			orderBy: $orderBy
			filter: $filter
			before: $before
			after: $after
		) @paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
				startCursor
				endCursor
			}
			facets {
				environments {
					value
					count
				}
				labels {
					key
					value
					count
				}
			}
			nodes {
				id
				__typename
				name
				teamEnvironment {
					environment {
						name
					}
				}
				team {
					slug
				}
				workload {
					__typename
					name
					teamEnvironment {
						environment {
							name
						}
					}
					team {
						slug
					}
				}
			}
		}

		externalResources {
			cdn {
				bucket
			}
		}
	}
}
