fragment SidebarActivityLogFragment on ActivityLogger
@arguments(filter: { type: "ActivityLogFilter" }, limit: { type: "Int" }) {
	activityLog(first: $limit, filter: $filter) {
		nodes {
			id
			actor
			message
			createdAt
			resourceName
			resourceType
			environmentName
			teamSlug
			__typename

			... on DeploymentActivityLogEntry {
				deploymentData: data {
					triggerURL
				}
			}
			... on GenericKubernetesResourceActivityLogEntry {
				genericKubernetesData: data {
					kind
					changedFields {
						field
						oldValue
						newValue
					}
				}
			}
			... on ApplicationScaledActivityLogEntry {
				appScaled: data {
					newSize
					direction
				}
			}
			... on ApplicationCreatedActivityLogEntry {
				id
			}
			... on ApplicationUpdatedActivityLogEntry {
				applicationUpdatedData: data {
					changedFields {
						field
						oldValue
						newValue
					}
				}
			}
			... on ClusterAuditActivityLogEntry {
				id
				clusterAuditData: data {
					action
					resourceKind
				}
			}

			... on RepositoryAddedActivityLogEntry {
				id
			}
			... on RepositoryRemovedActivityLogEntry {
				id
			}
			... on SecretCreatedActivityLogEntry {
				id
			}
			... on SecretDeletedActivityLogEntry {
				id
			}
			... on SecretUpdatedActivityLogEntry {
				secretUpdatedData: data {
					updatedFields {
						field
						oldValue
						newValue
					}
				}
			}
			... on SecretValueAddedActivityLogEntry {
				secretValueAddedData: data {
					valueName
				}
			}
			... on SecretValueUpdatedActivityLogEntry {
				secretValueUpdatedData: data {
					valueName
				}
			}
			... on SecretValueRemovedActivityLogEntry {
				secretValueRemovedData: data {
					valueName
				}
			}
			... on SecretValuesViewedActivityLogEntry {
				secretValuesViewedData: data {
					reason
				}
			}
			... on ConfigCreatedActivityLogEntry {
				id
			}
			... on ConfigDeletedActivityLogEntry {
				id
			}
			... on ConfigUpdatedActivityLogEntry {
				configUpdatedData: data {
					updatedFields {
						field
						oldValue
						newValue
					}
				}
			}
			... on TeamEnvironmentUpdatedActivityLogEntry {
				id
				teamEnvironmentUpdatedData: data {
					updatedFields {
						field
						oldValue
						newValue
					}
				}
			}
			... on TeamConfirmDeleteKeyActivityLogEntry {
				id
			}
			... on TeamCreateDeleteKeyActivityLogEntry {
				id
			}
			... on TeamCreatedActivityLogEntry {
				id
			}
			... on TeamDeployKeyUpdatedActivityLogEntry {
				id
			}
			... on JobRunDeletedActivityLogEntry {
				id
				jobRunDeletedData: data {
					runName
				}
			}
			... on JobCreatedActivityLogEntry {
				id
			}
			... on JobTriggeredActivityLogEntry {
				id
			}
			... on JobUpdatedActivityLogEntry {
				jobUpdatedData: data {
					changedFields {
						field
						oldValue
						newValue
					}
				}
			}
			... on TeamMemberAddedActivityLogEntry {
				addedData: data {
					role
					userEmail
					userID
				}
			}
			... on TeamMemberRemovedActivityLogEntry {
				removedData: data {
					userEmail
					userID
				}
			}
			... on TeamMemberSetRoleActivityLogEntry {
				setRoleData: data {
					role
					userEmail
					userID
				}
			}
			... on TeamUpdatedActivityLogEntry {
				id
				teamUpdatedData: data {
					updatedFields {
						field
						oldValue
						newValue
					}
				}
			}
			... on UnleashInstanceUpdatedActivityLogEntry {
				unleashInstanceUpdatedData: data {
					allowedTeamSlug
					revokedTeamSlug
					updatedReleaseChannel
				}
			}
			... on ApplicationRestartedActivityLogEntry {
				id
			}
			... on ApplicationDeletedActivityLogEntry {
				id
			}
			... on JobDeletedActivityLogEntry {
				id
			}
			... on CredentialsActivityLogEntry {
				credentialsData: data {
					permission
					ttl
				}
			}
			... on ServiceMaintenanceActivityLogEntry {
				id
			}
			... on ValkeyCreatedActivityLogEntry {
				id
			}
			... on ValkeyDeletedActivityLogEntry {
				id
			}
			... on ValkeyUpdatedActivityLogEntry {
				valkeyData: data {
					updatedFields {
						field
						newValue
						oldValue
					}
				}
			}
			... on OpenSearchCreatedActivityLogEntry {
				id
			}
			... on OpenSearchDeletedActivityLogEntry {
				id
			}
			... on PostgresDeletedActivityLogEntry {
				id
			}
			... on PostgresGrantAccessActivityLogEntry {
				postgresGrantAccessData: data {
					grantee
					until
				}
			}
			... on UnleashInstanceCreatedActivityLogEntry {
				id
			}
			... on UnleashInstanceDeletedActivityLogEntry {
				id
			}
			... on OpenSearchUpdatedActivityLogEntry {
				opensearchData: data {
					updatedFields {
						field
						newValue
						oldValue
					}
				}
			}
			... on VulnerabilityUpdatedActivityLogEntry {
				vulnerabilityUpdatedData: data {
					identifier
					package
					severity
					previousSuppression {
						state
						reason
					}
					newSuppression {
						state
						reason
					}
				}
			}
			... on ServiceAccountCreatedActivityLogEntry {
				id
			}
			... on ServiceAccountDeletedActivityLogEntry {
				id
			}
			... on ServiceAccountUpdatedActivityLogEntry {
				serviceAccountUpdatedData: data {
					updatedFields {
						field
						oldValue
						newValue
					}
				}
			}
			... on ServiceAccountTokenCreatedActivityLogEntry {
				serviceAccountTokenCreatedData: data {
					tokenName
				}
			}
			... on ServiceAccountTokenDeletedActivityLogEntry {
				serviceAccountTokenDeletedData: data {
					tokenName
				}
			}
			... on ServiceAccountTokenUpdatedActivityLogEntry {
				serviceAccountTokenUpdatedData: data {
					updatedFields {
						field
						oldValue
						newValue
					}
				}
			}
			... on RoleAssignedToServiceAccountActivityLogEntry {
				roleAssignedData: data {
					roleName
				}
			}
			... on RoleRevokedFromServiceAccountActivityLogEntry {
				roleRevokedData: data {
					roleName
				}
			}
			... on ServiceAccountWorkloadBindingAddedActivityLogEntry {
				workloadBindingAddedData: data {
					workloadName
					teamSlug
				}
			}
			... on ServiceAccountWorkloadBindingRemovedActivityLogEntry {
				workloadBindingRemovedData: data {
					workloadName
					teamSlug
				}
			}
		}
	}
}
