query Overview($team: Slug!) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		memUtil: appsUtilization(resourceType: MEMORY) {
			name
			env
			requested
			used
		}

		cpuUtil: appsUtilization(resourceType: CPU) {
			name
			env
			requested
			used
		}
	}
}
