query Overview($team: Slug!) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		memUtil: appsUtilization(resourceType: MEMORY) {
			app {
				name
				env {
					name
				}
			}

			requested
			used
		}

		cpuUtil: appsUtilization(resourceType: CPU) {
			app {
				name
				env {
					name
				}
			}
			requested
			used
		}
	}
}
