query Overview($team: Slug!) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		cpuUtil: workloadUtilization(resourceType: CPU) {
			requested
			used
			workload {
				name
				environment {
					name
				}
			}
		}
		memUtil: workloadUtilization(resourceType: MEMORY) {
			requested
			used
			workload {
				name
				environment {
					name
				}
			}
		}
		inventoryCounts {
			applications {
				total
			}
		}
	}
}
