query App($app: String!, $team: String!, $env: String!) {
	app(name: $app, team: $team, env: $env) {
		name
		ingresses
		image
		deployed
		...AppInstances
		...AppInstancesStatus
		...AccessPolicy
		...AutoScaling
		...Storage
		...Variables
		...Authz
	}
}
