query Jobs(
	$team: Slug!
	$orderBy: JobOrder
	$filter: TeamJobsFilter
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) @cache(policy: CacheAndNetwork, partial: true) {
	team(slug: $team) {
		slug
		jobs(
			first: $first
			last: $last
			orderBy: $orderBy
			filter: $filter
			before: $before
			after: $after
		) @paginate(mode: SinglePage) {
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
				pageEnd
				pageStart
				startCursor
				endCursor
			}

			facets {
				environments {
					value
					count
				}
				states {
					state
					count
				}
			}

			nodes {
				__typename
				id
				name
				schedule {
					expression
					timeZone
					nextRun
				}
				teamEnvironment {
					environment {
						name
					}
				}
				team {
					slug
				}
				runs(first: 1) {
					pageInfo {
						totalCount
					}

					edges {
						node {
							startTime
							status {
								state
								message
							}
						}
					}
				}
				issues {
					pageInfo {
						totalCount
					}
					edges {
						node {
							severity
						}
					}
				}
				state
				deployments(first: 1) {
					nodes {
						createdAt
					}
				}
			}
		}
	}
}
