query TeamRoles($team: Slug!) {
	team(slug: $team) {
		viewerIsOwner
		viewerIsMember
		deletionInProgress
		inventoryCounts {
			applications {
				total
				notNais
			}
			bigQueryDatasets {
				total
			}
			buckets {
				total
			}
			jobs {
				total
				notNais
			}
			kafkaTopics {
				total
			}
			openSearchInstances {
				total
			}
			redisInstances {
				total
			}
			sqlInstances {
				total
			}
		}
	}
}
