query TeamRoles($team: Slug!) {
	team(slug: $team) {
		members {
			pageInfo {
				totalCount
			}
		}
		viewerIsOwner
		viewerIsMember
		deletionInProgress
		lastSuccessfulSync
		externalResources {
			gitHubTeam {
				slug
			}
		}
		purpose
		slackChannel
	}
}
