query TeamOverview($team: Slug!) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		purpose
		activityLog(first: 1) {
			nodes {
				id
				...ActivityLogEntryFragment
			}
		}
		workloads(first: 600) {
			nodes {
				__typename
				id
				name
				team {
					slug
				}
				teamEnvironment {
					environment {
						name
					}
				}

				status {
					errors {
						level
						... on WorkloadStatusDeprecatedRegistry {
							name
							registry
							repository
							tag
						}
						... on WorkloadStatusSynchronizationFailing {
							detail
						}
						... on WorkloadStatusInvalidNaisYaml {
							detail
						}
						... on WorkloadStatusNoRunningInstances {
							level
						}
						... on WorkloadStatusFailedRun {
							detail
							name
						}
						... on WorkloadStatusVulnerable {
							__typename
							summary {
								riskScore
								critical
							}
						}
					}
				}
			}
		}
	}
}
