query TeamOverview($team: Slug!, $severitySince: Time!, $activityLogFilter: ActivityLogFilter!)
@cache(policy: NetworkOnly) {
	team(slug: $team) {
		firingAlerts: alerts(filter: { states: [FIRING] }) {
			pageInfo {
				totalCount
			}
			nodes {
				id
				name
				state
				teamEnvironment {
					environment {
						name
					}
				}
			}
		}

		pendingAlerts: alerts(filter: { states: [PENDING] }) {
			pageInfo {
				totalCount
			}
			nodes {
				id
				name
				state
				teamEnvironment {
					environment {
						name
					}
				}
			}
		}

		todos: issues(filter: { severity: TODO }) {
			pageInfo {
				totalCount
			}
		}
		warnings: issues(filter: { severity: WARNING }) {
			pageInfo {
				totalCount
			}
		}
		critical: issues(filter: { severity: CRITICAL }) {
			pageInfo {
				totalCount
			}
		}

		deployments(first: 10) {
			pageInfo {
				totalCount
			}
			nodes {
				id
				statuses {
					nodes {
						state
						message
						createdAt
					}
				}
				resources {
					nodes {
						id
						kind
						name
					}
				}
				environmentName
				createdAt
				teamSlug
				repository
				commitSha
				deployerUsername
				triggerUrl
			}
		}

		workloads {
			pageInfo {
				totalCount
			}

			nodes {
				id
				image {
					vulnerabilities(filter: { severity: CRITICAL, severitySince: $severitySince }) {
						nodes {
							id
							severity
							severitySince
						}
					}
				}
			}
		}

		vulnerabilitySummary {
			bomCount
			coverage
			critical
			riskScore
			riskScoreTrend
			lastUpdated
		}
		...SidebarActivityLogFragment @with(limit: 15, filter: $activityLogFilter) @mask_disable
	}
}
