query TeamOverview($team: Slug!) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		firingAlerts: alerts(filter: { states: [FIRING] }) {
			pageInfo {
				totalCount
			}
			nodes {
				id
				name
				state
				teamEnvironment {
					environment {
						name
					}
				}
			}
		}

		todos: issues(filter: { severity: TODO }) {
			pageInfo {
				totalCount
			}
		}
		warnings: issues(filter: { severity: WARNING }) {
			pageInfo {
				totalCount
			}
		}
		criticals: issues(filter: { severity: CRITICAL }) {
			pageInfo {
				totalCount
			}
		}

		issues(first: 10, orderBy: { field: SEVERITY, direction: ASC }) {
			pageInfo {
				totalCount
			}
			nodes {
				id
				__typename

				teamEnvironment {
					environment {
						name
					}
				}
				...IssueFragment
			}
		}

		deployments(first: 10) {
			pageInfo {
				totalCount
			}
			nodes {
				id
				statuses {
					nodes {
						state
						message
						createdAt
					}
				}
				resources {
					nodes {
						id
						kind
						name
					}
				}
				environmentName
				createdAt
				teamSlug
				repository
				commitSha
				deployerUsername
				triggerUrl
			}
		}
	}
}
