query TeamOverview($team: Slug!) @cache(policy: NetworkOnly) {
	currentUnitPrices {
		cpu {
			value
		}
		memory {
			value
		}
	}
	team(slug: $team) {
		environments {
			id
			gcpProjectID
			environment {
				name
			}
		}
		purpose

		deployments(first: 10) {
			pageInfo {
				totalCount
			}
			nodes {
				id
				statuses {
					nodes {
						state
						message
						createdAt
					}
				}
				resources {
					nodes {
						id
						kind
						name
					}
				}
				environmentName
				createdAt
				teamSlug
				repository
				commitSha
				deployerUsername
				triggerUrl
			}
		}

		workloads {
			pageInfo {
				totalCount
			}
		}

		statuses: workloads(
			first: 50
			filter: { states: [NOT_NAIS, FAILING] }
			orderBy: { field: STATUS, direction: DESC }
		) {
			pageInfo {
				totalCount
			}
			nodes {
				__typename
				id
				name
				team {
					slug
				}
				teamEnvironment {
					environment {
						name
					}
				}

				status {
					errors {
						__typename
						level
						... on WorkloadStatusDeprecatedRegistry {
							name
							registry
							repository
							tag
						}
						... on WorkloadStatusSynchronizationFailing {
							detail
						}
						... on WorkloadStatusInvalidNaisYaml {
							detail
						}
						... on WorkloadStatusNoRunningInstances {
							level
						}
						... on WorkloadStatusFailedRun {
							detail
							name
						}
					}
				}
			}
		}
		vulnerabilitySummary {
			bomCount
			coverage
			critical
			riskScore
			riskScoreTrend
			ranking
			lastUpdated
		}
		...SidebarActivityLogFragment @with(first: 3)
	}
}
