query TeamRoles($team: Slug!) {
	team(slug: $team) {
		members {
			pageInfo {
				totalCount
			}
		}
		userIsOwner
		userIsMember
		deletionInProgress
		lastSuccessfulSync
		externalResources {
			gitHubTeam {
				slug
			}
		}
		purpose
	}
}
