query ActivityLog(
	$team: Slug!
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
	$filter: ActivityLogFilter
) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		slug
		activityLog(first: $first, last: $last, before: $before, after: $after, filter: $filter)
			@paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				pageEnd
				pageStart
				totalCount
				startCursor
				endCursor
			}
			nodes {
				id
				__typename
				...ActivityLogEntryFragment
			}
		}
	}
}
