query BigQuery($team: Slug!, $orderBy: BigQueryDatasetOrder, $from: Date!, $to: Date!) {
	team(slug: $team) @loading {
		cost @loading {
			daily(from: $from, to: $to, filter: { services: ["BigQuery"] }) {
				sum
			}
		}
		bigQueryDatasets(first: 20, orderBy: $orderBy) @paginate(mode: SinglePage) @loading {
			pageInfo @loading {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
				startCursor
				endCursor
			}
			nodes @loading {
				name
				environment {
					name
				}
				workload {
					__typename
					name
					environment {
						name
					}
					team {
						slug
					}
				}
			}
		}
	}
}
