query BigQuery($team: Slug!, $orderBy: BigQueryDatasetOrder) {
	team(slug: $team) @loading {
		bigQueryDatasets(first: 20, orderBy: $orderBy) @paginate(mode: SinglePage) @loading {
			pageInfo @loading {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
			}
			nodes @loading {
				name
				environment {
					name
				}
				workload {
					__typename
					name
					environment {
						name
					}
					team {
						slug
					}
				}
			}
		}
	}
}
