query TeamDeployments($limit: Int, $offset: Int, $team: Slug!) @loading(cascade: true) {
	team(slug: $team) {
		id
		deployments(limit: $limit, offset: $offset) {
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
			}
			nodes @loading(count: 10) {
				id
				created
				env
				repository
				resources {
					group
					kind
					version
					name
					namespace
				}
				statuses {
					created
					message
					status
				}
			}
		}
	}
}
