query TeamDeployments($team: Slug!) {
	team(slug: $team) {
		deployments(first: 20) @paginate(mode: SinglePage) {
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
			}
			edges {
				node {
					id
					created
					environment {
						name
					}
					repository
					resources {
						group
						kind
						version
						name
						namespace
					}
					statuses {
						created
						message
						status
					}
				}
			}
		}
	}
}
