query ApplicationIssues(
	$team: Slug!
	$env: String!
	$app: String!
	$filter: ResourceIssueFilter
	$orderBy: IssueOrder
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) @cache(policy: NetworkOnly) {
	team(slug: $team) {
		slug
		environment(name: $env) {
			id
			application(name: $app) {
				id
				name
				issues(
					first: $first
					last: $last
					filter: $filter
					orderBy: $orderBy
					before: $before
					after: $after
				) @paginate(mode: SinglePage) {
					pageInfo {
						startCursor
						endCursor
						hasNextPage
						hasPreviousPage
						pageStart
						pageEnd
						totalCount
					}
					nodes {
						id
						__typename

						teamEnvironment {
							environment {
								name
							}
						}
						...IssueFragment
					}
				}
			}
		}
	}
}
