query OpenSearch($team: Slug!, $orderBy: OpenSearchOrder, $from: Date!, $to: Date!) {
	team(slug: $team) @loading {
		cost @loading {
			daily(from: $from, to: $to, filter: { services: ["OpenSearch"] }) {
				sum
			}
		}
		openSearchInstances(first: 20, orderBy: $orderBy) @paginate(mode: SinglePage) @loading {
			pageInfo @loading {
				hasNextPage
				hasPreviousPage
				totalCount
				pageStart
				pageEnd
				startCursor
				endCursor
			}
			nodes @loading {
				name
				environment {
					name
				}
				workload {
					__typename
					name
					environment {
						name
					}
					team {
						slug
					}
				}
			}
		}
	}
}
