query OpenSearch(
	$team: Slug!
	$orderBy: OpenSearchOrder
	$from: Date!
	$to: Date!
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) {
	team(slug: $team) {
		cost {
			daily(from: $from, to: $to, filter: { services: ["OpenSearch"] }) {
				sum
			}
		}

		totalCount: openSearchInstances {
			pageInfo {
				totalCount
			}
		}

		openSearchInstances(
			first: $first
			last: $last
			orderBy: $orderBy
			before: $before
			after: $after
		) @paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				totalCount
				pageStart
				pageEnd
				startCursor
				endCursor
			}
			nodes {
				__typename
				name
				environment {
					name
				}
				team {
					slug
				}
				workload {
					__typename
					name
					environment {
						name
					}
					team {
						slug
					}
				}
			}
		}
	}
}
