query Teams {
	teams(first: 50) @paginate(mode: SinglePage) {
		totalCount
		pageInfo {
			hasNextPage
			hasPreviousPage
			startCursor
			endCursor
			from
			to
		}
		edges {
			node {
				description
				name
			}
		}
	}
}
