query ResourceUtilizationForApp( # $team: Slug! # $app: String!
	# $env: String!
	$start: Time!
	$end: Time! # $start: Time!
	$step: Int!
) # $end: Time!
# $step: Int!
# $resourceType: ResourceTypeV2!
{
	memory: resourceUtilizationForAppV2(
		env: "dev"
		team: "etterlatte"
		app: "etterlatte-api"
		start: $start
		end: $end
		step: $step
		resourceType: MEMORY
	) {
		timestamp
		value
	}
	cpu: resourceUtilizationForAppV2(
		env: "dev"
		team: "etterlatte"
		app: "etterlatte-api"
		start: $start
		end: $end
		step: $step
		resourceType: CPU
	) {
		timestamp
		value
	}
}
