query ResourceUtilizationForApp(
	$team: Slug! 
	$app: String!
	$env: String!
	$start: Time!
	$end: Time!
	$step: Int!
) 
{
  app(name:$app, env:$env, team:$team){
    name
    utilization{
      memory: range(start:$start, end:$end, step:$step, resourceType:MEMORY){
        timestamp
        value
      }
      cpu: range(start:$start, end:$end, step:$step, resourceType:CPU){
        timestamp
        value
      }
    }
  }
}
