query TeamResourceUsage($team: Slug!) {
	currentUnitPrices {
		cpu {
			value
		}
		memory {
			value
		}
	}
	team(slug: $team) {
		cpuUtil: workloadUtilization(resourceType: CPU) {
			workload {
				id
				name
				__typename
				teamEnvironment {
					environment {
						name
					}
				}
			}
			requested
			used
		}

		memUtil: workloadUtilization(resourceType: MEMORY) {
			workload {
				id
				name
				__typename
				teamEnvironment {
					environment {
						name
					}
				}
			}
			requested
			used
		}
	}
}
