query CVEDetails($identifier: String!) @cache(policy: CacheAndNetwork) {
	cve(identifier: $identifier) {
		id
		identifier
		title
		severity
		priority
		cvssScore
		epssPercentile
		hasKevEntry
		knownRansomwareUse
		detailsLink
	}
}
