query CVEDetails($identifier: String!) {
	cve(identifier: $identifier) {
		id
		identifier
		title
		severity
		detailsLink
		riskAssessment {
			cvssScore
			priority
			epssScore
			epssPercentile
			hasKevEntry
			knownRansomwareUse
		}
	}
}
