query CVEWorkloads($identifier: String!, $first: Int, $last: Int, $after: Cursor, $before: Cursor)
@cache(policy: CacheAndNetwork) {
	cve(identifier: $identifier) {
		id
		workloads(first: $first, last: $last, after: $after, before: $before) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				startCursor
				endCursor
				totalCount
				pageStart
				pageEnd
			}
			nodes {
				workload {
					__typename
					name
					team {
						slug
					}
					teamEnvironment {
						environment {
							name
						}
					}
					image {
						name
						tag
					}
				}
				vulnerability {
					identifier
					severity
					package
					suppression {
						state
					}
				}
			}
		}
	}
}
