query ServiceAccountDetail($id: ID!) @cache(policy: CacheAndNetwork) {
	serviceAccount(id: $id) {
		id
		name
		description
		createdAt
		updatedAt
		lastUsedAt
		workloadBindings {
			edges {
				node {
					workloadName
					environment
				}
			}
		}
		...ServiceAccountRolesFragment
		...ServiceAccountAuthenticationFragment
		...ResourceActivityCardServiceAccountFragment
	}
	roles(first: 100, filter: { excludeGlobalRoles: true }) {
		edges {
			node {
				name
				description
			}
		}
	}
}
