query UserSyncLogs {
	userSyncLog(first: 20) @paginate(mode: SinglePage) {
		edges {
			node {
				... on UserUpdatedUserSyncLogEntry {
					id
					createdAt
					message
					userName
					userEmail
					oldUserName
					oldUserEmail
				}
				... on RoleAssignedUserSyncLogEntry {
					id
					createdAt
					message
					userName
					userEmail
					roleName
				}
				... on RoleRevokedUserSyncLogEntry {
					id
					createdAt
					message
					userName
					userEmail
					roleName
				}
			}
		}

		pageInfo {
			hasNextPage
			hasPreviousPage
			pageStart
			pageEnd
			totalCount
			startCursor
			endCursor
		}
	}
}
