query Valkey(
	$team: Slug!
	$orderBy: ValkeyInstanceOrder
	$from: Date!
	$to: Date!
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) @blocking {
	team(slug: $team) {
		slug
		cost {
			daily(from: $from, to: $to, filter: { services: ["Valkey"] }) {
				series {
					date
					sum
				}
			}
		}

		valkeyInstances(first: $first, last: $last, orderBy: $orderBy, before: $before, after: $after)
			@paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				totalCount
				pageStart
				pageEnd
				startCursor
				endCursor
			}
			nodes {
				id
				__typename
				name
				team {
					slug
				}
				environment {
					name
				}
				workload {
					__typename
					name
					environment {
						name
					}
					team {
						slug
					}
				}
			}
		}
	}
}
