query Valkeys(
	$team: Slug!
	$orderBy: ValkeyOrder
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) @cache(policy: CacheAndNetwork) {
	team(slug: $team) {
		slug

		valkeys(first: $first, last: $last, orderBy: $orderBy, before: $before, after: $after)
			@paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				totalCount
				pageStart
				pageEnd
				startCursor
				endCursor
			}
			nodes {
				id
				__typename
				name
				team {
					slug
				}
				teamEnvironment {
					environment {
						name
					}
				}
				state
				issues {
					pageInfo {
						totalCount
					}
					edges {
						node {
							severity
						}
					}
				}
			}
		}
	}
}
