query Valkeys(
	$team: Slug!
	$orderBy: ValkeyOrder
	$from: Date!
	$to: Date!
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) @cache(policy: CacheAndNetwork) {
	team(slug: $team) {
		slug
		cost {
			daily(from: $from, to: $to, filter: { services: ["Valkey"] }) {
				series {
					services {
						service
					}
					date
					sum
				}
			}
		}

		valkeys(first: $first, last: $last, orderBy: $orderBy, before: $before, after: $after)
			@paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				totalCount
				pageStart
				pageEnd
				startCursor
				endCursor
			}
			nodes {
				id
				__typename
				name
				team {
					slug
				}
				teamEnvironment {
					environment {
						name
					}
				}
				state
				issues {
					pageInfo {
						totalCount
					}
					edges {
						node {
							severity
						}
					}
				}
				workload {
					__typename
					name
					teamEnvironment {
						environment {
							name
						}
					}
					team {
						slug
					}
				}
			}
		}
	}
}
