query TeamServiceAccounts($team: Slug!, $first: Int, $last: Int, $before: Cursor, $after: Cursor)
@cache(policy: CacheAndNetwork) {
	team(slug: $team) {
		serviceAccounts(first: $first, last: $last, before: $before, after: $after)
			@paginate(mode: SinglePage) {
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
				pageEnd
				pageStart
				startCursor
				endCursor
			}
			edges {
				node {
					id
					name
					description
					createdAt
					lastUsedAt
				}
			}
		}
	}
}
