query Members($team: String!) {
	team(name: $team) {
		name
		members(first: 10) @paginate(mode: SinglePage) {
			totalCount
			pageInfo {
				hasNextPage
				hasPreviousPage
				startCursor
				endCursor
				from
				to
			}
			edges {
				node {
					email
					name
					role
				}
			}
		}
	}
}
