query Members($limit: Int, $offset: Int, $team: Slug!) @loading(cascade: true) {
	team(slug: $team) {
		slug
		members(limit: $limit, offset: $offset) {
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
			}
			nodes @loading(count: 10) {
				user {
					id
					email
					name
				}
				role
			}
		}
	}
}
