query Members($team: String!) @loading(cascade: true) {
	team(name: $team) {
		name
		members(first: 10) @paginate(mode: SinglePage) {
			totalCount
			pageInfo {
				hasNextPage
				hasPreviousPage
				startCursor
				endCursor
				from
				to
			}
			edges @loading(count: 10) {
				node {
					email
					name
					role
				}
			}
		}
	}
}
