query Repositories($team: Slug!, $orderBy: RepositoryOrder, $filter: TeamRepositoryFilter)
@cache(policy: NetworkOnly) {
	team(slug: $team) @loading {
		repositories(first: 20, orderBy: $orderBy, filter: $filter)
			@paginate(mode: SinglePage)
			@loading {
			pageInfo @loading {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
				startCursor
				endCursor
			}
			nodes @loading {
				name
				team {
					slug
				}
			}
		}
		viewerIsOwner @loading
		viewerIsMember @loading
	}
}
