query Repositories($team: Slug!, $orderBy: RepositoryOrder, $filter: TeamRepositoryFilter)
@cache(policy: NetworkOnly) {
	team(slug: $team) {
		repositories(first: 20, orderBy: $orderBy, filter: $filter) @paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
				startCursor
				endCursor
			}
			nodes {
				id
				name
				team {
					slug
				}
			}
		}
		viewerIsOwner
		viewerIsMember
	}
}
