query Bucket($env: String!, $team: Slug!, $name: String!) @loading(cascade: true) {
	bucket(env: $env, team: $team, name: $name) {
		id
		name
		env {
			name
		}
		workload {
			... on App {
				name
			}
			... on NaisJob {
				name
			}
		}
	}
}
