query SqlInstances($team: Slug!, $orderBy: SqlInstanceOrder, $from: Date!, $to: Date!) @blocking {
	team(slug: $team) {
		cost {
			daily(from: $from, to: $to, filter: { services: ["Cloud SQL"] }) {
				sum
			}
		}
		serviceUtilization {
			sqlInstances {
				cpu {
					requested
					utilization
				}
				disk {
					requested
					utilization
				}
				memory {
					requested
					utilization
				}
			}
		}
		sqlInstances(first: 20, orderBy: $orderBy) @paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
				startCursor
				endCursor
			}
			nodes {
				id
				__typename
				name
				environment {
					name
				}
				team {
					slug
				}
				connectionName
				state
				version
				cost {
					sum
				}
				metrics {
					cpu {
						cores
						utilization
					}
					memory {
						quotaBytes
						utilization
					}
					disk {
						quotaBytes
						utilization
					}
				}

				workload {
					name
				}
			}
		}
	}
}
