query PostgresInstances(
	$team: Slug!
	$orderBy: PostgresInstanceOrder
	$filter: PostgresInstanceFilter
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
) @cache(policy: CacheAndNetwork, partial: true) {
	team(slug: $team) {
		slug
		inventoryCounts {
			sqlInstances {
				total
			}
		}

		postgresInstances(
			first: $first
			last: $last
			orderBy: $orderBy
			filter: $filter
			before: $before
			after: $after
		) @paginate(mode: SinglePage) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
				startCursor
				endCursor
			}
			facets {
				environments {
					value
					count
				}
				states {
					state
					count
				}
				majorVersions {
					value
					count
				}
				highAvailability {
					value
					count
				}
				labels {
					key
					value
					count
				}
			}
			edges {
				node {
					id
					__typename
					name
					teamEnvironment {
						environment {
							name
						}
					}
					team {
						slug
					}
					majorVersion
					state
				}
			}
		}
	}
}
