query Teams(
	$first: Int
	$last: Int
	$before: Cursor
	$after: Cursor
	$filter: TeamFilter
	$orderBy: TeamOrder
) {
	teams(
		first: $first
		last: $last
		before: $before
		after: $after
		filter: $filter
		orderBy: $orderBy
	) @paginate(mode: SinglePage) {
		pageInfo {
			hasNextPage
			hasPreviousPage
			pageStart
			pageEnd
			totalCount
			startCursor
			endCursor
		}
		edges {
			node {
				slug
				members {
					pageInfo {
						totalCount
					}
				}

				inventoryCounts {
					applications {
						total
					}
					bigQueryDatasets {
						total
					}
					buckets {
						total
					}
					jobs {
						total
					}
					kafkaTopics {
						total
					}
					openSearchInstances {
						total
					}
					sqlInstances {
						total
					}
					valkeyInstances {
						total
					}
				}
			}
		}
	}
}
