query TeamVulnerabilities(
	$limit: Int
	$offset: Int
	$team: Slug!
	$orderBy: OrderBy = { field: SEVERITY_CRITICAL, direction: DESC }
) {
	team(slug: $team) @loading {
		id @loading
		slug
		vulnerabilities(limit: $limit, offset: $offset, orderBy: $orderBy) @loading {
			pageInfo @loading {
				totalCount
				hasNextPage
				hasPreviousPage
			}

			nodes @loading(count: 10) {
				appName
				env
				findingsLink
				hasBom
				summary {
					riskScore
					unassigned
					total
					critical
					high
					medium
					low
				}
			}
		}
	}
}
