query TeamVulnerabilities(
	$limit: Int
	$offset: Int
	$team: Slug!
	$orderBy: OrderBy = { field: SEVERITY_CRITICAL, direction: DESC }
) @loading(count: 5, cascade: true) {
	team(slug: $team) {
		id
		vulnerabilities(limit: $limit, offset: $offset, orderBy: $orderBy) @loading {
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
			}

			nodes {
				appName
				env
				findingsLink
				hasBom
				summary {
					riskScore
					unassigned
					total
					critical
					high
					medium
					low
				}
			}
		}
	}
}
