query TeamVulnerabilities($team: String!, $orderBy: VulnerabilitiesOrderBy = {
	field: SEVERITY_CRITICAL
	direction: DESC
}) @loading(count: 5, cascade: true) {
	team(name: $team) {
		id
		vulnerabilitiesForTeam(first: 30, orderBy: $orderBy) @loading @paginate(mode: SinglePage) {
			totalCount
			pageInfo {
				hasNextPage
				hasPreviousPage
				startCursor
				endCursor
				from
				to
			}

			edges {
				node {
					appName
					env
					project {
						projectName
						findingsLink
						summary{
							critical
							high
							medium
							low
						}
					}
				}
			}
		}
	}
}
