query ServiceAccountDetail($team: Slug!, $after: Cursor) @cache(policy: CacheAndNetwork) {
	team(slug: $team) {
		serviceAccounts(first: 50, after: $after) {
			pageInfo {
				hasNextPage
				endCursor
			}
			nodes {
				id
				name
				description
				createdAt
				updatedAt
				lastUsedAt
				...ServiceAccountRolesFragment
				...ServiceAccountAuthenticationFragment
			}
		}
	}
	...AvailableRolesFragment
}
