query BigQueryDataset($env: String!, $team: Slug!, $name: String!) @loading(cascade: true) {
	team(slug: $team) {
		bigQueryDataset(env: $env, name: $name) {
			cascadingDelete
			description
			cost
			id
			name
			status {
				conditions {
					reason
					type
					status
					message
					lastTransitionTime
				}
				lastModifiedTime
				creationTime
			}
			env {
				name
			}

			workload {
				name
				type: __typename
			}
			access {
				role
				email
			}
		}
	}
}
