query BigQueryDataset($environment: String!, $team: Slug!, $name: String!) {
	team(slug: $team) {
		environment(name: $environment) {
			name
			bigQueryDataset(name: $name) {
				cascadingDelete
				description
				cost {
					sum
				}
				id
				name
				status {
					creationTime
					lastModifiedTime
				}
				environment {
					name
				}
				workload {
					name
					__typename
					environment {
						name
					}
					team {
						slug
					}
				}
				access {
					edges {
						node {
							role
							email
						}
					}
				}
			}
		}
	}
}
