query AppNotificationState($app: String!, $team: String!, $env: String!)
@cache(policy: NetworkOnly) {
	app(name: $app, team: $team, env: $env) {
		appState {
			state
			errors {
				level
			}
		}
	}
}
