query AppNotificationState($app: String!, $team: Slug!, $env: String!) @loading {
	app(name: $app, team: $team, env: $env) @loading {
		name @loading

		appState {
			state @loading

			errors {
				__typename
				...AppErrorFragment
			}
		}
		instances {
			name
			state
			message
		}
		accessPolicy {
			inbound {
				rules {
					application
					namespace
					cluster
					mutual
				}
			}
			outbound {
				rules {
					application
					namespace
					cluster
					mutual
				}
			}
		}
	}
}
