query App($app: String!, $team: Slug!, $env: String!) {
	team(slug: $team) {
		environment(name: $env) {
			application(name: $app) {
				__typename
				id
				name
				team {
					slug
				}
				image {
					tag
				}
				instances {
					nodes {
						image {
							name
							tag
						}
					}
				}
				deletionStartedAt
				deployments(first: 1) {
					nodes {
						triggerUrl
						statuses {
							nodes {
								state
								message
								createdAt
							}
						}
					}
				}

				...AppInstances
				...AppStatus
				...AppUtilization
				...Persistence
				...WorkloadDeploy
				...WorkloadImage
				...NetworkPolicy
				...Manifest
				...Ingresses
			}
		}
	}
}
