query App($app: String!, $team: Slug!, $env: String!) @cache(policy: NetworkOnly) {
	app(name: $app, team: $team, env: $env) @loading(cascade: true) {
		name
		ingresses

		image
		secrets
		instances {
			name
			image
		}

		...AccessPolicy
		...AppImage
		...AppInstances
		...AppInstancesStatus
		...Authz
		...AutoScaling
		...Storage
		...AppStatus
	}
}
