query App($app: String!, $team: Slug!, $env: String!) {
	team(slug: $team) {
		environment(name: $env) {
			application(name: $app) {
				name
				...AppInstances
				...AppPersistence
				...AppStatus
				...AppUtilization
				...Scaling
				...TrafficPolicy
				...WorkloadImage
			}
		}
		viewerIsMember
		viewerIsOwner
	}
}
