query App($app: String!, $team: Slug!, $env: String!) {
	team(slug: $team) {
		environment(name: $env) {
			application(name: $app) {
				__typename
				id
				name
				team {
					slug
				}
				issues {
					edges {
						node {
							id
							__typename
							message
							...IssueFragment
						}
					}
				}
				teamEnvironment {
					environment {
						name
					}
				}

				deletionStartedAt
				deployments(first: 1) {
					nodes {
						triggerUrl
						statuses {
							nodes {
								state
								message
								createdAt
							}
						}
					}
				}

				ingresses {
					type
					url
					metrics {
						errorsPerSecond
						requestsPerSecond
					}
				}

				instanceGroups {
					id
					name
					image {
						name
						tag
					}
					created
					readyInstances
					desiredInstances
					instances {
						id
						name
						status {
							state
						}
						restarts
					}
				}

				...SidebarActivityLogFragment @with(limit: 20) @mask_disable
				...Persistence
				...WorkloadDeploy
				...NetworkPolicy
				...Manifest
			}
		}
	}
}
