query App($app: String!, $team: Slug!, $env: String!) {
	team(slug: $team) {
		environment(name: $env) {
			application(name: $app) {
				__typename
				id
				name
				team {
					slug
				}
				image {
					hasSBOM
					vulnerabilitySummary {
						critical
						high
						medium
						low
						unassigned
						riskScore
						lastUpdated
					}
				}
				issues {
					edges {
						node {
							id
							__typename
							message
							...IssueFragment
						}
					}
				}
				teamEnvironment {
					environment {
						name
					}
				}

				deletionStartedAt
				deployments(first: 1) {
					nodes {
						triggerUrl
						statuses {
							nodes {
								state
								message
								createdAt
							}
						}
					}
				}

				ingresses {
					type
					url
					metrics {
						errorsPerSecond
						requestsPerSecond
					}
				}

				resources {
					scaling {
						maxInstances
						minInstances
						strategies {
							__typename
							... on KafkaLagScalingStrategy {
								consumerGroup
								threshold
								topicName
							}
							... on CPUScalingStrategy {
								threshold
							}
						}
					}
					requests {
						cpu
						memory
					}
					limits {
						cpu
						memory
					}
				}

				utilization {
					requested_cpu: requested(resourceType: CPU)
					requested_memory: requested(resourceType: MEMORY)
					limit_cpu: limit(resourceType: CPU)
					limit_memory: limit(resourceType: MEMORY)
					current_cpu: current(resourceType: CPU)
					current_memory: current(resourceType: MEMORY)
					recommendations {
						cpuRequestCores
						memoryLimitBytes
						memoryRequestBytes
					}
				}

				...SidebarActivityLogFragment @with(limit: 20) @mask_disable
				...Persistence
				...WorkloadDeploy
				...NetworkPolicy
				...Manifest
			}
		}
	}
}
