query App($app: String!, $team: Slug!, $env: String!) {
	team(slug: $team) {
		environment(name: $env) {
			application(name: $app) {
				__typename
				id
				name
				team {
					slug
				}
				image {
					sbom {
						status
						processingStartedAt
					}
					vulnerabilitySummary {
						critical
						high
						medium
						low
						unassigned
						riskScore
						lastUpdated
					}
				}
				issues {
					edges {
						node {
							id
							__typename
							severity
							message
							...IssueFragment
						}
					}
				}
				criticalIssues: issues(filter: { severity: CRITICAL }) {
					pageInfo {
						totalCount
					}
				}
				warningIssues: issues(filter: { severity: WARNING }) {
					pageInfo {
						totalCount
					}
				}
				todoIssues: issues(filter: { severity: TODO }) {
					pageInfo {
						totalCount
					}
				}
				teamEnvironment {
					environment {
						name
					}
				}

				deletionStartedAt
				deployments(first: 1) {
					nodes {
						triggerUrl
						statuses {
							nodes {
								state
								message
								createdAt
							}
						}
					}
				}

				...Persistence
				...WorkloadDeploy
				...Manifest
			}
		}
	}
}
