query Jobs($team: String!, $orderBy: OrderBy = { field: STATUS, direction: ASC })
@loading(count: 5, cascade: true) {
	team(name: $team) {
		id
		naisjobs(first: 50, orderBy: $orderBy) @paginate(mode: SinglePage) {
			totalCount
			pageInfo {
				hasNextPage
				hasPreviousPage
				startCursor
				endCursor
				from
				to
			}

			edges {
				node {
					deployInfo {
						timestamp
					}
					name
					image
					env {
						name
					}
					jobState {
						state
					}
				}
			}
		}
	}
}
