query ApplicationImageDetails($team: Slug!, $env: String!, $app: String!)
@cache(policy: NetworkOnly) {
	team(slug: $team) @loading {
		slug @loading
		environment(name: $env) @loading {
			name @loading
			workload(name: $app) @loading {
				__typename
				name @loading
				image @loading {
					name @loading
					tag
					hasSBOM

					vulnerabilitySummary @loading {
						critical
						high
						medium
						low
						unassigned
						riskScore
					}

					...ImageWorkloadReferences
				}
			}
		}
		viewerIsMember @loading
	}
}
