query ApplicationImageDetails($team: Slug!, $env: String!, $app: String!) {
	team(slug: $team) {
		environment(name: $env) {
			workload(name: $app) {
				__typename
				image {
					name
					tag
					hasSBOM

					vulnerabilitySummary {
						critical
						high
						medium
						low
						unassigned
						riskScore
					}

					#vulnerabilities(first: 10) @paginate(mode: SinglePage) {
					#	edges {
					#		node {
					#			description
					#			identifier
					#			package
					#			severity
					#			state
					#		}
					#	}
					#}

					...ImageVulnerabilities
					...WorkloadRefs
				}
			}
		}
		viewerIsMember
	}
}
