query TeamSettings($team: Slug!) {
	team(slug: $team) @loading {
		id
		slug
		purpose
		slackChannel
		gitHubTeamSlug
		azureGroupID
		googleGroupEmail
		googleArtifactRegistry
		cdnBucket
		environments {
			name
			gcpProjectID
			slackAlertsChannel
		}
		auditEntries(first: 5) {
			pageInfo {
				hasNextPage
				hasPreviousPage
				totalCount
				pageStart
				pageEnd
			}
			edges {
				node {
					actor
					message
					createdAt
				}
			}
		}
	}
}
