query People($after: Cursor, $before: Cursor, $first: Int, $last: Int, $orderBy: UserOrder) {
	users(after: $after, before: $before, first: $first, last: $last, orderBy: $orderBy) {
		pageInfo {
			endCursor
			hasNextPage
			hasPreviousPage
			pageEnd
			pageStart
			startCursor
			totalCount
		}

		edges {
			node {
				id
				name
				email
				externalID
				teams {
					nodes {
						role
						team {
							id
							slug
						}
					}
				}
			}
		}
	}
}
