import { graphql as gql } from '../gql';

/**
 * Page size used for the UserTeams query. Mirrors the value previously used by
 * the Houdini-based query in `src/routes/query.gql`.
 */
export const USER_TEAMS_PAGE_SIZE = 25;

/**
 * Typed UserTeams query.
 *
 * The `graphql()` helper is generated by GraphQL Code Generator's `client`
 * preset (see `codegen.ts`). It returns a `TypedDocumentNode` so urql can
 * infer both the result and variables types from the GraphQL schema —
 * no hand-maintained TypeScript interfaces required.
 *
 * NOTE: The generated helper is imported under the alias `gql` because the
 * Houdini Vite plugin rewrites any `graphql(...)` call expression in the
 * project (regardless of import source), which would otherwise replace this
 * call's return value and break urql at runtime.
 */
export const UserTeamsQuery = gql(/* GraphQL */ `
	query UserTeams($first: Int, $after: Cursor, $last: Int, $before: Cursor) {
		me {
			__typename
			... on User {
				teams(first: $first, after: $after, last: $last, before: $before) {
					pageInfo {
						hasNextPage
						hasPreviousPage
						pageEnd
						pageStart
						startCursor
						endCursor
						totalCount
					}
					nodes {
						team {
							id
							slug
							purpose
						}
					}
				}
			}
		}
	}
`);
