query TeamCost($team: Slug!, $from: Date!, $to: Date!) @cache(policy: NetworkOnly) {
	dailyCostForTeam(team: $team, from: $from, to: $to) @loading {
		series {
			costType
			sum
			data {
				date
				cost
			}
		}
	}
}
