name: Build and push image and chart
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

env:
  NAME: console-frontend
  IMAGE_REPOSITORY: oci://europe-north1-docker.pkg.dev/nais-io/nais
jobs:
  build_push:
    outputs:
      version: ${{ steps.build-push-sign.outputs.version }}
    permissions:
      contents: "read"
      id-token: "write"
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7
      - uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # ratchet:jdx/mise-action@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Sync SvelteKit
        run: pnpm exec svelte-kit sync
      - name: Type check
        run: pnpm run check
      - name: Lint
        run: pnpm run lint
      - name: Run tests
        run: pnpm run test -- --run
      - id: node_version
        run: echo "node_version=$(mise current node)" >> $GITHUB_OUTPUT
      - uses: nais/platform-build-push-sign@07a21e2293624a78499c79eeea3ce6d314f8a8d9 # ratchet:nais/platform-build-push-sign@main
        id: build-push-sign
        with:
          name: ${{ env.NAME }}
          google_service_account: gh-${{ env.NAME }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          push: true
          build_args: |
            NODE_VERSION=${{ steps.node_version.outputs.node_version }}
      - uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # ratchet:azure/setup-helm@v5
        name: "Setup Helm"
        with:
          version: "3.8.0"
      - name: Build Chart
        run: |-
          sed -i "s/^version: .*/version: ${{ steps.build-push-sign.outputs.version }}/g" charts/Chart.yaml
          cat charts/Chart.yaml
          helm package charts
      - name: Push Chart
        run: |-
          helm push ${{ env.NAME }}*.tgz ${{ env.IMAGE_REPOSITORY }}
  deploy:
    name: Deploy
    needs:
      - build_push
    # Only do this if on main
    if: endsWith(github.ref, '/main')
    runs-on: fasit-deploy
    permissions:
      id-token: write
    steps:
      - uses: nais/fasit-deploy@53e433b1bdd08fc622e03a78584c0832c9083bd3 # ratchet:nais/fasit-deploy@v4
        with:
          chart: ${{ env.IMAGE_REPOSITORY }}/${{ env.NAME }}
          version: ${{ needs.build_push.outputs.version }}
          targets: |
            [
              { "target": { "kind": "management", "tenant": "ci-nais" }, "wait": true },
              { "target": { "kind": "management" } }
            ]
