query SqlInstances($team: Slug!, $orderBy: SqlInstanceOrder, $from: Date!, $to: Date!) {
	team(slug: $team) @loading {
		cost @loading {
			daily(from: $from, to: $to, filter: { services: ["Cloud SQL"] }) {
				sum
			}
		}
		serviceUtilization @loading {
			sqlInstances @loading {
				cpu {
					requested
					utilization
				}
				disk {
					requested
					utilization
				}
				memory {
					requested
					utilization
				}
			}
		}
		sqlInstances(first: 20, orderBy: $orderBy) @paginate(mode: SinglePage) @loading {
			pageInfo @loading {
				hasNextPage
				hasPreviousPage
				pageStart
				pageEnd
				totalCount
			}
			nodes @loading {
				name
				environment {
					name
				}

				connectionName
				state
				version
				cost {
					sum
				}
				metrics {
					cpu {
						cores
						utilization
					}
					memory {
						quotaBytes
						utilization
					}
					disk {
						quotaBytes
						utilization
					}
				}

				workload {
					name
				}
			}
		}
	}
}
