query SqlInstances(
	$team: Slug!
	$orderBy: OrderBy = { field: NAME, direction: ASC }
	$limit: Int
	$offset: Int
) @loading(count: 5, cascade: true) {
	team(slug: $team) {
		id
		sqlInstances(limit: $limit, offset: $offset, orderBy: $orderBy) {
			metrics {
				cost
				cpu {
					cores
					utilization
				}
				memory {
					quotaBytes
					utilization
				}
				disk {
					quotaBytes
					utilization
				}
			}
			pageInfo {
				totalCount
				hasNextPage
				hasPreviousPage
			}
			nodes {
				id
				name
				env {
					name
				}
				isHealthy
				type
				connectionName
				workload {
					... on App {
						name
					}
					... on NaisJob {
						name
					}
				}
				metrics {
					cost
					cpu {
						cores
						utilization
					}
					memory {
						quotaBytes
						utilization
					}
					disk {
						quotaBytes
						utilization
					}
				}
				highAvailability
			}
		}
	}
}
