query DataProduct {
	teams {
		nodes {
			inventoryCounts {
				applications {
					total
				}
				bigQueryDatasets {
					total
				}
				buckets {
					total
				}
				jobs {
					total
				}
				kafkaTopics {
					total
				}
				openSearchInstances {
					total
				}
				redisInstances {
					total
				}
				sqlInstances {
					total
				}
			}
		}
	}
}
