query DataProduct {
	currentUnitPrices {
		cpu {
			value
		}
		memory {
			value
		}
	}
	teams(first: 1000) {
		nodes {
			inventoryCounts {
				applications {
					total
				}
				bigQueryDatasets {
					total
				}
				buckets {
					total
				}
				jobs {
					total
				}
				kafkaTopics {
					total
				}
				openSearchInstances {
					total
				}
				valkeyInstances {
					total
				}
				sqlInstances {
					total
				}
			}
		}
	}
}
